version: "3.8"
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  cbawrapper:
    build: .
    container_name: cbawrapper
    restart: always
    ports:
      - "8500:8500"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/admin
