package com.neptune.cbawrapper.Services;

import com.neptune.cbawrapper.Models.Bank;
import com.neptune.cbawrapper.Models.Lgas;
import com.neptune.cbawrapper.Models.States;
import com.neptune.cbawrapper.Repository.BankRepository;
import com.neptune.cbawrapper.Repository.LgaRepository;
import com.neptune.cbawrapper.Repository.StateRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class SeederService implements CommandLineRunner {

    private final BankRepository bankRepository;
    private final StateRepository stateRepository;
    private final LgaRepository lgaRepository;

    public SeederService(BankRepository bankRepository, StateRepository stateRepository, LgaRepository lgaRepository) {
        this.bankRepository = bankRepository;
        this.stateRepository = stateRepository;
        this.lgaRepository = lgaRepository;
    }

    @Override
    public void run(String... args) {
        seedBanks();
        seedStates();
        seedLgas();
    }

    public void seedBanks() {

        // Prevent duplicate insert
        if (bankRepository.count() > 0) {
            return;
        }

        List<Bank> banks = new ArrayList<>();

        banks.add(Bank.builder().serialNumber(1).bankName("ACCESS BANK PLC").bankCode("044").build());
        banks.add(Bank.builder().serialNumber(2).bankName("CITI BANK").bankCode("023").build());
        banks.add(Bank.builder().serialNumber(3).bankName("DIAMOND BANK PLC").bankCode("063").build());
        banks.add(Bank.builder().serialNumber(4).bankName("ECOBANK NIGERIA PLC").bankCode("050").build());
        banks.add(Bank.builder().serialNumber(5).bankName("ENTERPRISE BANK PLC").bankCode("084").build());
        banks.add(Bank.builder().serialNumber(6).bankName("FIDELITY BANK PLC").bankCode("070").build());
        banks.add(Bank.builder().serialNumber(7).bankName("FIRST BANK OF NIGERIA").bankCode("011").build());
        banks.add(Bank.builder().serialNumber(8).bankName("FIRST CITY MONUMENT BANK").bankCode("214").build());
        banks.add(Bank.builder().serialNumber(9).bankName("GLOBUS BANK").bankCode("103").build());
        banks.add(Bank.builder().serialNumber(10).bankName("GUARANTY TRUST BANK PLC").bankCode("058").build());
        banks.add(Bank.builder().serialNumber(11).bankName("HERITAGE BANK").bankCode("030").build());
        banks.add(Bank.builder().serialNumber(12).bankName("JAIZ BANK").bankCode("301").build());
        banks.add(Bank.builder().serialNumber(13).bankName("KEYSTONE BANK PLC").bankCode("082").build());
        banks.add(Bank.builder().serialNumber(14).bankName("LOTUS BANK").bankCode("303").build());
        banks.add(Bank.builder().serialNumber(15).bankName("MAIN STREET BANK NIGERIA").bankCode("014").build());
        banks.add(Bank.builder().serialNumber(16).bankName("PARALEX BANK").bankCode("104").build());
        banks.add(Bank.builder().serialNumber(17).bankName("POLARIS BANK").bankCode("076").build());
        banks.add(Bank.builder().serialNumber(18).bankName("PROVIDUS BANK").bankCode("101").build());
        banks.add(Bank.builder().serialNumber(19).bankName("SKYE BANK PLC").bankCode("076").build());
        banks.add(Bank.builder().serialNumber(20).bankName("STANBIC IBTC BANK PLC").bankCode("221").build());
        banks.add(Bank.builder().serialNumber(21).bankName("STANDARD CHARTERED BANK PLC").bankCode("068").build());
        banks.add(Bank.builder().serialNumber(22).bankName("STERLING BANK PLC").bankCode("232").build());
        banks.add(Bank.builder().serialNumber(23).bankName("TAJ BANK").bankCode("302").build());
        banks.add(Bank.builder().serialNumber(26).bankName("Titantrust BANK").bankCode("102").build());
        banks.add(Bank.builder().serialNumber(27).bankName("UNION BANK OF NIGERIA").bankCode("032").build());
        banks.add(Bank.builder().serialNumber(28).bankName("UNITED BANK FOR AFRICA").bankCode("033").build());
        banks.add(Bank.builder().serialNumber(29).bankName("UNITY BANK PLC").bankCode("215").build());
        banks.add(Bank.builder().serialNumber(30).bankName("WEMA BANK PLC").bankCode("035").build());
        banks.add(Bank.builder().serialNumber(31).bankName("ZENITH INTERNATIONAL BANK PLC").bankCode("057").build());

        bankRepository.saveAll(banks);

        System.out.println("All banks seeded successfully.");
    }

    public void seedStates() {

        // Prevent duplicate inserts
        if (stateRepository.count() > 0) {
            return;
        }

        List<States> states = new ArrayList<>();

        states.add(States.builder().serialNumber(1).stateName("ABIA").stateCode("AB").build());
        states.add(States.builder().serialNumber(2).stateName("ADAMAWA").stateCode("AD").build());
        states.add(States.builder().serialNumber(3).stateName("AKWA IBOM").stateCode("AK").build());
        states.add(States.builder().serialNumber(4).stateName("ANAMBRA").stateCode("AN").build());
        states.add(States.builder().serialNumber(5).stateName("BAUCHI").stateCode("BA").build());
        states.add(States.builder().serialNumber(6).stateName("BAYELSA").stateCode("BY").build());
        states.add(States.builder().serialNumber(7).stateName("BENUE").stateCode("BE").build());
        states.add(States.builder().serialNumber(8).stateName("BORNO").stateCode("BO").build());
        states.add(States.builder().serialNumber(9).stateName("CROSS RIVER").stateCode("CR").build());
        states.add(States.builder().serialNumber(10).stateName("DELTA").stateCode("DE").build());
        states.add(States.builder().serialNumber(11).stateName("EBONYI").stateCode("EB").build());
        states.add(States.builder().serialNumber(12).stateName("EDO").stateCode("ED").build());
        states.add(States.builder().serialNumber(13).stateName("EKITI").stateCode("EK").build());
        states.add(States.builder().serialNumber(14).stateName("ENUGU").stateCode("EN").build());
        states.add(States.builder().serialNumber(15).stateName("ABUJA").stateCode("FC").build());
        states.add(States.builder().serialNumber(16).stateName("GOMBE").stateCode("GO").build());
        states.add(States.builder().serialNumber(17).stateName("IMO").stateCode("IM").build());
        states.add(States.builder().serialNumber(18).stateName("JIGAWA").stateCode("JI").build());
        states.add(States.builder().serialNumber(19).stateName("KADUNA").stateCode("KD").build());
        states.add(States.builder().serialNumber(20).stateName("KANO").stateCode("KN").build());
        states.add(States.builder().serialNumber(21).stateName("KATSINA").stateCode("KT").build());
        states.add(States.builder().serialNumber(22).stateName("KEBBI").stateCode("KE").build());
        states.add(States.builder().serialNumber(23).stateName("KOGI").stateCode("KO").build());
        states.add(States.builder().serialNumber(24).stateName("KWARA").stateCode("KW").build());
        states.add(States.builder().serialNumber(25).stateName("LAGOS").stateCode("LA").build());
        states.add(States.builder().serialNumber(26).stateName("NASARAWA").stateCode("NA").build());
        states.add(States.builder().serialNumber(27).stateName("NIGER").stateCode("NI").build());
        states.add(States.builder().serialNumber(28).stateName("OGUN").stateCode("OG").build());
        states.add(States.builder().serialNumber(29).stateName("ONDO").stateCode("ON").build());
        states.add(States.builder().serialNumber(30).stateName("OSUN").stateCode("OS").build());
        states.add(States.builder().serialNumber(31).stateName("OYO").stateCode("OY").build());
        states.add(States.builder().serialNumber(32).stateName("PLATEAU").stateCode("PL").build());
        states.add(States.builder().serialNumber(33).stateName("RIVER").stateCode("RI").build());
        states.add(States.builder().serialNumber(34).stateName("SOKOTO").stateCode("SO").build());
        states.add(States.builder().serialNumber(35).stateName("TARABA").stateCode("TA").build());
        states.add(States.builder().serialNumber(36).stateName("YOBE").stateCode("YO").build());
        states.add(States.builder().serialNumber(37).stateName("ZAMFARA").stateCode("ZA").build());

        stateRepository.saveAll(states);

        System.out.println("All states seeded successfully.");
    }

    public void seedLgas() {

        // Prevent duplicate inserts
        if (lgaRepository.count() > 0) {
            return;
        }

        List<Lgas> lgas = new ArrayList<>();

        lgas.add(Lgas.builder().lgaName("Aba North").stateCode("AB").lgaCode("AB001").build());
        lgas.add(Lgas.builder().lgaName("Aba South").stateCode("AB").lgaCode("AB002").build());
        lgas.add(Lgas.builder().lgaName("Arochukwu").stateCode("AB").lgaCode("AB003").build());
        lgas.add(Lgas.builder().lgaName("Bende").stateCode("AB").lgaCode("AB004").build());
        lgas.add(Lgas.builder().lgaName("Ikwuano").stateCode("AB").lgaCode("AB005").build());
        lgas.add(Lgas.builder().lgaName("Isiala Ngwa North").stateCode("AB").lgaCode("AB006").build());
        lgas.add(Lgas.builder().lgaName("Isiala Ngwa South").stateCode("AB").lgaCode("AB007").build());
        lgas.add(Lgas.builder().lgaName("Isuikwuato").stateCode("AB").lgaCode("AB008").build());
        lgas.add(Lgas.builder().lgaName("Obi Ngwa").stateCode("AB").lgaCode("AB009").build());
        lgas.add(Lgas.builder().lgaName("Ohafia").stateCode("AB").lgaCode("AB010").build());
        lgas.add(Lgas.builder().lgaName("Osisioma").stateCode("AB").lgaCode("AB011").build());
        lgas.add(Lgas.builder().lgaName("Ugwunagbo").stateCode("AB").lgaCode("AB012").build());
        lgas.add(Lgas.builder().lgaName("Ukwa East").stateCode("AB").lgaCode("AB013").build());
        lgas.add(Lgas.builder().lgaName("Ukwa West").stateCode("AB").lgaCode("AB014").build());
        lgas.add(Lgas.builder().lgaName("Umuahia North").stateCode("AB").lgaCode("AB015").build());
        lgas.add(Lgas.builder().lgaName("Umuahia South").stateCode("AB").lgaCode("AB016").build());
        lgas.add(Lgas.builder().lgaName("Umu Nneochi").stateCode("AB").lgaCode("AB017").build());
        lgas.add(Lgas.builder().lgaName("ABXXXX").stateCode("AB").lgaCode("ABXXX").build());
        lgas.add(Lgas.builder().lgaName("Demsa").stateCode("AD").lgaCode("AD001").build());
        lgas.add(Lgas.builder().lgaName("Fufure").stateCode("AD").lgaCode("AD002").build());
        lgas.add(Lgas.builder().lgaName("Ganye").stateCode("AD").lgaCode("AD003").build());
        lgas.add(Lgas.builder().lgaName("Grie").stateCode("AD").lgaCode("AD004").build());
        lgas.add(Lgas.builder().lgaName("Gombi").stateCode("AD").lgaCode("AD005").build());
        lgas.add(Lgas.builder().lgaName("Gayuk").stateCode("AD").lgaCode("AD006").build());
        lgas.add(Lgas.builder().lgaName("Hong").stateCode("AD").lgaCode("AD007").build());
        lgas.add(Lgas.builder().lgaName("Jada").stateCode("AD").lgaCode("AD008").build());
        lgas.add(Lgas.builder().lgaName("Larmurde").stateCode("AD").lgaCode("AD009").build());
        lgas.add(Lgas.builder().lgaName("Madagali").stateCode("AD").lgaCode("AD010").build());
        lgas.add(Lgas.builder().lgaName("Maiha").stateCode("AD").lgaCode("AD011").build());
        lgas.add(Lgas.builder().lgaName("Mayo Belwa").stateCode("AD").lgaCode("AD012").build());
        lgas.add(Lgas.builder().lgaName("Michika").stateCode("AD").lgaCode("AD013").build());
        lgas.add(Lgas.builder().lgaName("Mubi North").stateCode("AD").lgaCode("AD014").build());
        lgas.add(Lgas.builder().lgaName("Mubi South").stateCode("AD").lgaCode("AD015").build());
        lgas.add(Lgas.builder().lgaName("Numan").stateCode("AD").lgaCode("AD016").build());
        lgas.add(Lgas.builder().lgaName("Shelleng").stateCode("AD").lgaCode("AD017").build());
        lgas.add(Lgas.builder().lgaName("Song").stateCode("AD").lgaCode("AD018").build());
        lgas.add(Lgas.builder().lgaName("Toungo").stateCode("AD").lgaCode("AD019").build());
        lgas.add(Lgas.builder().lgaName("Yola North").stateCode("AD").lgaCode("AD020").build());
        lgas.add(Lgas.builder().lgaName("Yola South").stateCode("AD").lgaCode("AD021").build());
        lgas.add(Lgas.builder().lgaName("ADXXXX").stateCode("AD").lgaCode("ADXXX").build());
        lgas.add(Lgas.builder().lgaName("Eket").stateCode("AK").lgaCode("AK001").build());
        lgas.add(Lgas.builder().lgaName("Onna").stateCode("AK").lgaCode("AK002").build());
        lgas.add(Lgas.builder().lgaName("Nsit-Ubium").stateCode("AK").lgaCode("AK003").build());
        lgas.add(Lgas.builder().lgaName("Etinan").stateCode("AK").lgaCode("AK004").build());
        lgas.add(Lgas.builder().lgaName("Mkpat-Enin").stateCode("AK").lgaCode("AK005").build());
        lgas.add(Lgas.builder().lgaName("Uyo").stateCode("AK").lgaCode("AK006").build());
        lgas.add(Lgas.builder().lgaName("Ibiono-Ibom").stateCode("AK").lgaCode("AK007").build());
        lgas.add(Lgas.builder().lgaName("Itu").stateCode("AK").lgaCode("AK008").build());
        lgas.add(Lgas.builder().lgaName("Urue-Offong/Oruko").stateCode("AK").lgaCode("AK009").build());
        lgas.add(Lgas.builder().lgaName("Okobo").stateCode("AK").lgaCode("AK010").build());
        lgas.add(Lgas.builder().lgaName("Oron").stateCode("AK").lgaCode("AK011").build());
        lgas.add(Lgas.builder().lgaName("Etim Ekpo").stateCode("AK").lgaCode("AK012").build());
        lgas.add(Lgas.builder().lgaName("Ika").stateCode("AK").lgaCode("AK013").build());
        lgas.add(Lgas.builder().lgaName("Abak").stateCode("AK").lgaCode("AK014").build());
        lgas.add(Lgas.builder().lgaName("Ini").stateCode("AK").lgaCode("AK015").build());
        lgas.add(Lgas.builder().lgaName("Essien Udim").stateCode("AK").lgaCode("AK016").build());
        lgas.add(Lgas.builder().lgaName("Ikono").stateCode("AK").lgaCode("AK017").build());
        lgas.add(Lgas.builder().lgaName("Ikot Ekpene").stateCode("AK").lgaCode("AK018").build());
        lgas.add(Lgas.builder().lgaName("Obot Akara").stateCode("AK").lgaCode("AK019").build());
        lgas.add(Lgas.builder().lgaName("Ukanafun").stateCode("AK").lgaCode("AK020").build());
        lgas.add(Lgas.builder().lgaName("Esit Eket").stateCode("AK").lgaCode("AK021").build());
        lgas.add(Lgas.builder().lgaName("Mbo").stateCode("AK").lgaCode("AK022").build());
        lgas.add(Lgas.builder().lgaName("Eastern Obolo").stateCode("AK").lgaCode("AK023").build());
        lgas.add(Lgas.builder().lgaName("Ibeno").stateCode("AK").lgaCode("AK024").build());
        lgas.add(Lgas.builder().lgaName("Ikot Abasi").stateCode("AK").lgaCode("AK025").build());
        lgas.add(Lgas.builder().lgaName("Udung-Uko").stateCode("AK").lgaCode("AK026").build());
        lgas.add(Lgas.builder().lgaName("Oruk Anam").stateCode("AK").lgaCode("AK027").build());
        lgas.add(Lgas.builder().lgaName("Ibesikpo Asutan").stateCode("AK").lgaCode("AK028").build());
        lgas.add(Lgas.builder().lgaName("Nsit-Ibom").stateCode("AK").lgaCode("AK029").build());
        lgas.add(Lgas.builder().lgaName("Uruan").stateCode("AK").lgaCode("AK030").build());
        lgas.add(Lgas.builder().lgaName("Nsit-Atai").stateCode("AK").lgaCode("AK031").build());
        lgas.add(Lgas.builder().lgaName("AKXXXX").stateCode("AK").lgaCode("AKXXX").build());
        lgas.add(Lgas.builder().lgaName("Aguata").stateCode("AN").lgaCode("AN001").build());
        lgas.add(Lgas.builder().lgaName("Anambra East").stateCode("AN").lgaCode("AN002").build());
        lgas.add(Lgas.builder().lgaName("Anambra West").stateCode("AN").lgaCode("AN003").build());
        lgas.add(Lgas.builder().lgaName("Anaocha").stateCode("AN").lgaCode("AN004").build());
        lgas.add(Lgas.builder().lgaName("Awka North").stateCode("AN").lgaCode("AN005").build());
        lgas.add(Lgas.builder().lgaName("Awka South").stateCode("AN").lgaCode("AN006").build());
        lgas.add(Lgas.builder().lgaName("Ayamelum").stateCode("AN").lgaCode("AN007").build());
        lgas.add(Lgas.builder().lgaName("Dunukofia").stateCode("AN").lgaCode("AN008").build());
        lgas.add(Lgas.builder().lgaName("Ekwusigo").stateCode("AN").lgaCode("AN009").build());
        lgas.add(Lgas.builder().lgaName("Idemili North").stateCode("AN").lgaCode("AN010").build());
        lgas.add(Lgas.builder().lgaName("Idemili South").stateCode("AN").lgaCode("AN011").build());
        lgas.add(Lgas.builder().lgaName("Ihiala").stateCode("AN").lgaCode("AN012").build());
        lgas.add(Lgas.builder().lgaName("Njikoka").stateCode("AN").lgaCode("AN013").build());
        lgas.add(Lgas.builder().lgaName("Nnewi North").stateCode("AN").lgaCode("AN014").build());
        lgas.add(Lgas.builder().lgaName("Nnewi South").stateCode("AN").lgaCode("AN015").build());
        lgas.add(Lgas.builder().lgaName("Ogbaru").stateCode("AN").lgaCode("AN016").build());
        lgas.add(Lgas.builder().lgaName("Onitsha North").stateCode("AN").lgaCode("AN017").build());
        lgas.add(Lgas.builder().lgaName("Onitsha South").stateCode("AN").lgaCode("AN018").build());
        lgas.add(Lgas.builder().lgaName("Orumba North").stateCode("AN").lgaCode("AN019").build());
        lgas.add(Lgas.builder().lgaName("Orumba South").stateCode("AN").lgaCode("AN020").build());
        lgas.add(Lgas.builder().lgaName("Oyi").stateCode("AN").lgaCode("AN021").build());
        lgas.add(Lgas.builder().lgaName("ANXXXX").stateCode("AN").lgaCode("ANXXX").build());
        lgas.add(Lgas.builder().lgaName("Alkaleri").stateCode("BA").lgaCode("BA001").build());
        lgas.add(Lgas.builder().lgaName("Bauchi").stateCode("BA").lgaCode("BA002").build());
        lgas.add(Lgas.builder().lgaName("Bogoro").stateCode("BA").lgaCode("BA003").build());
        lgas.add(Lgas.builder().lgaName("Damban").stateCode("BA").lgaCode("BA004").build());
        lgas.add(Lgas.builder().lgaName("Darazo").stateCode("BA").lgaCode("BA005").build());
        lgas.add(Lgas.builder().lgaName("Dass").stateCode("BA").lgaCode("BA006").build());
        lgas.add(Lgas.builder().lgaName("Gamawa").stateCode("BA").lgaCode("BA007").build());
        lgas.add(Lgas.builder().lgaName("Ganjuwa").stateCode("BA").lgaCode("BA008").build());
        lgas.add(Lgas.builder().lgaName("Giade").stateCode("BA").lgaCode("BA009").build());
        lgas.add(Lgas.builder().lgaName("Itas/Gadau").stateCode("BA").lgaCode("BA010").build());
        lgas.add(Lgas.builder().lgaName("Jamaare").stateCode("BA").lgaCode("BA011").build());
        lgas.add(Lgas.builder().lgaName("Katagum").stateCode("BA").lgaCode("BA012").build());
        lgas.add(Lgas.builder().lgaName("Kirfi").stateCode("BA").lgaCode("BA013").build());
        lgas.add(Lgas.builder().lgaName("Misau").stateCode("BA").lgaCode("BA014").build());
        lgas.add(Lgas.builder().lgaName("Ningi").stateCode("BA").lgaCode("BA015").build());
        lgas.add(Lgas.builder().lgaName("Shira").stateCode("BA").lgaCode("BA016").build());
        lgas.add(Lgas.builder().lgaName("Tafawa Balewa").stateCode("BA").lgaCode("BA017").build());
        lgas.add(Lgas.builder().lgaName("Toro").stateCode("BA").lgaCode("BA018").build());
        lgas.add(Lgas.builder().lgaName("Warji").stateCode("BA").lgaCode("BA019").build());
        lgas.add(Lgas.builder().lgaName("Zaki").stateCode("BA").lgaCode("BA020").build());
        lgas.add(Lgas.builder().lgaName("BAXXXX").stateCode("BA").lgaCode("BAXXX").build());
        lgas.add(Lgas.builder().lgaName("Guma").stateCode("BE").lgaCode("BE001").build());
        lgas.add(Lgas.builder().lgaName("Makurdi").stateCode("BE").lgaCode("BE002").build());
        lgas.add(Lgas.builder().lgaName("Gwer East").stateCode("BE").lgaCode("BE003").build());
        lgas.add(Lgas.builder().lgaName("Tarka").stateCode("BE").lgaCode("BE004").build());
        lgas.add(Lgas.builder().lgaName("Buruku").stateCode("BE").lgaCode("BE005").build());
        lgas.add(Lgas.builder().lgaName("Gboko").stateCode("BE").lgaCode("BE006").build());
        lgas.add(Lgas.builder().lgaName("Logo").stateCode("BE").lgaCode("BE007").build());
        lgas.add(Lgas.builder().lgaName("Katsina-Ala").stateCode("BE").lgaCode("BE008").build());
        lgas.add(Lgas.builder().lgaName("Ukum").stateCode("BE").lgaCode("BE009").build());
        lgas.add(Lgas.builder().lgaName("Obi").stateCode("BE").lgaCode("BE010").build());
        lgas.add(Lgas.builder().lgaName("Konshisha").stateCode("BE").lgaCode("BE011").build());
        lgas.add(Lgas.builder().lgaName("Ushongo").stateCode("BE").lgaCode("BE012").build());
        lgas.add(Lgas.builder().lgaName("Kwande").stateCode("BE").lgaCode("BE013").build());
        lgas.add(Lgas.builder().lgaName("Oju").stateCode("BE").lgaCode("BE014").build());
        lgas.add(Lgas.builder().lgaName("Vandeikya").stateCode("BE").lgaCode("BE015").build());
        lgas.add(Lgas.builder().lgaName("Ohimini").stateCode("BE").lgaCode("BE016").build());
        lgas.add(Lgas.builder().lgaName("Agatu").stateCode("BE").lgaCode("BE017").build());
        lgas.add(Lgas.builder().lgaName("Apa").stateCode("BE").lgaCode("BE018").build());
        lgas.add(Lgas.builder().lgaName("Gwer West").stateCode("BE").lgaCode("BE019").build());
        lgas.add(Lgas.builder().lgaName("Oturkpo").stateCode("BE").lgaCode("BE020").build());
        lgas.add(Lgas.builder().lgaName("Ogbadibo").stateCode("BE").lgaCode("BE021").build());
        lgas.add(Lgas.builder().lgaName("Okpokwu").stateCode("BE").lgaCode("BE022").build());
        lgas.add(Lgas.builder().lgaName("Ado").stateCode("BE").lgaCode("BE023").build());
        lgas.add(Lgas.builder().lgaName("BEXXXX").stateCode("BE").lgaCode("BEXXX").build());
        lgas.add(Lgas.builder().lgaName("Abadam").stateCode("BO").lgaCode("BO001").build());
        lgas.add(Lgas.builder().lgaName("Askira/Uba").stateCode("BO").lgaCode("BO002").build());
        lgas.add(Lgas.builder().lgaName("Bama").stateCode("BO").lgaCode("BO003").build());
        lgas.add(Lgas.builder().lgaName("Bayo").stateCode("BO").lgaCode("BO004").build());
        lgas.add(Lgas.builder().lgaName("Biu").stateCode("BO").lgaCode("BO005").build());
        lgas.add(Lgas.builder().lgaName("Chibok").stateCode("BO").lgaCode("BO006").build());
        lgas.add(Lgas.builder().lgaName("Damboa").stateCode("BO").lgaCode("BO007").build());
        lgas.add(Lgas.builder().lgaName("Dikwa").stateCode("BO").lgaCode("BO008").build());
        lgas.add(Lgas.builder().lgaName("Gubio").stateCode("BO").lgaCode("BO009").build());
        lgas.add(Lgas.builder().lgaName("Guzamala").stateCode("BO").lgaCode("BO010").build());
        lgas.add(Lgas.builder().lgaName("Gwoza").stateCode("BO").lgaCode("BO011").build());
        lgas.add(Lgas.builder().lgaName("Hawul").stateCode("BO").lgaCode("BO012").build());
        lgas.add(Lgas.builder().lgaName("Jere").stateCode("BO").lgaCode("BO013").build());
        lgas.add(Lgas.builder().lgaName("Kaga").stateCode("BO").lgaCode("BO014").build());
        lgas.add(Lgas.builder().lgaName("Kala/Balge").stateCode("BO").lgaCode("BO015").build());
        lgas.add(Lgas.builder().lgaName("Konduga").stateCode("BO").lgaCode("BO016").build());
        lgas.add(Lgas.builder().lgaName("Kukawa").stateCode("BO").lgaCode("BO017").build());
        lgas.add(Lgas.builder().lgaName("Kwaya Kusar").stateCode("BO").lgaCode("BO018").build());
        lgas.add(Lgas.builder().lgaName("Mafa").stateCode("BO").lgaCode("BO019").build());
        lgas.add(Lgas.builder().lgaName("Magumeri").stateCode("BO").lgaCode("BO020").build());
        lgas.add(Lgas.builder().lgaName("Maiduguri").stateCode("BO").lgaCode("BO021").build());
        lgas.add(Lgas.builder().lgaName("Marte").stateCode("BO").lgaCode("BO022").build());
        lgas.add(Lgas.builder().lgaName("Mobbar").stateCode("BO").lgaCode("BO023").build());
        lgas.add(Lgas.builder().lgaName("Monguno").stateCode("BO").lgaCode("BO024").build());
        lgas.add(Lgas.builder().lgaName("Ngala").stateCode("BO").lgaCode("BO025").build());
        lgas.add(Lgas.builder().lgaName("Nganzai").stateCode("BO").lgaCode("BO026").build());
        lgas.add(Lgas.builder().lgaName("Shani").stateCode("BO").lgaCode("BO027").build());
        lgas.add(Lgas.builder().lgaName("BOXXXX").stateCode("BO").lgaCode("BOXXX").build());
        lgas.add(Lgas.builder().lgaName("Kolokuma/Opokuma").stateCode("BY").lgaCode("BY001").build());
        lgas.add(Lgas.builder().lgaName("Yenagoa").stateCode("BY").lgaCode("BY002").build());
        lgas.add(Lgas.builder().lgaName("Nembe").stateCode("BY").lgaCode("BY003").build());
        lgas.add(Lgas.builder().lgaName("Ogbia").stateCode("BY").lgaCode("BY004").build());
        lgas.add(Lgas.builder().lgaName("Southern Ijaw").stateCode("BY").lgaCode("BY005").build());
        lgas.add(Lgas.builder().lgaName("Brass").stateCode("BY").lgaCode("BY006").build());
        lgas.add(Lgas.builder().lgaName("Ekeremor").stateCode("BY").lgaCode("BY007").build());
        lgas.add(Lgas.builder().lgaName("Sagbama").stateCode("BY").lgaCode("BY008").build());
        lgas.add(Lgas.builder().lgaName("BYXXXX").stateCode("BY").lgaCode("BYXXX").build());
        lgas.add(Lgas.builder().lgaName("Abi").stateCode("CR").lgaCode("CR001").build());
        lgas.add(Lgas.builder().lgaName("Akamkpa").stateCode("CR").lgaCode("CR002").build());
        lgas.add(Lgas.builder().lgaName("Akpabuyo").stateCode("CR").lgaCode("CR003").build());
        lgas.add(Lgas.builder().lgaName("Bekwarra").stateCode("CR").lgaCode("CR004").build());
        lgas.add(Lgas.builder().lgaName("Biase").stateCode("CR").lgaCode("CR005").build());
        lgas.add(Lgas.builder().lgaName("Boki").stateCode("CR").lgaCode("CR006").build());
        lgas.add(Lgas.builder().lgaName("Calabar Municipal").stateCode("CR").lgaCode("CR007").build());
        lgas.add(Lgas.builder().lgaName("Calabar South").stateCode("CR").lgaCode("CR008").build());
        lgas.add(Lgas.builder().lgaName("Etung").stateCode("CR").lgaCode("CR009").build());
        lgas.add(Lgas.builder().lgaName("Ikom").stateCode("CR").lgaCode("CR010").build());
        lgas.add(Lgas.builder().lgaName("Obanliku").stateCode("CR").lgaCode("CR011").build());
        lgas.add(Lgas.builder().lgaName("Obubra").stateCode("CR").lgaCode("CR012").build());
        lgas.add(Lgas.builder().lgaName("Obudu").stateCode("CR").lgaCode("CR013").build());
        lgas.add(Lgas.builder().lgaName("Odukpani").stateCode("CR").lgaCode("CR014").build());
        lgas.add(Lgas.builder().lgaName("Ogoja").stateCode("CR").lgaCode("CR015").build());
        lgas.add(Lgas.builder().lgaName("Yakuur").stateCode("CR").lgaCode("CR016").build());
        lgas.add(Lgas.builder().lgaName("Yala").stateCode("CR").lgaCode("CR017").build());
        lgas.add(Lgas.builder().lgaName("Bakassi").stateCode("CR").lgaCode("CR019").build());
        lgas.add(Lgas.builder().lgaName("CRXXXX").stateCode("CR").lgaCode("CRXXX").build());
        lgas.add(Lgas.builder().lgaName("Aniocha North").stateCode("DE").lgaCode("DE001").build());
        lgas.add(Lgas.builder().lgaName("Aniocha South").stateCode("DE").lgaCode("DE002").build());
        lgas.add(Lgas.builder().lgaName("Bomadi").stateCode("DE").lgaCode("DE003").build());
        lgas.add(Lgas.builder().lgaName("Burutu").stateCode("DE").lgaCode("DE004").build());
        lgas.add(Lgas.builder().lgaName("Ethiope East").stateCode("DE").lgaCode("DE005").build());
        lgas.add(Lgas.builder().lgaName("Ethiope West").stateCode("DE").lgaCode("DE006").build());
        lgas.add(Lgas.builder().lgaName("Ika North East").stateCode("DE").lgaCode("DE007").build());
        lgas.add(Lgas.builder().lgaName("Ika South").stateCode("DE").lgaCode("DE008").build());
        lgas.add(Lgas.builder().lgaName("Isoko North").stateCode("DE").lgaCode("DE009").build());
        lgas.add(Lgas.builder().lgaName("Isoko South").stateCode("DE").lgaCode("DE010").build());
        lgas.add(Lgas.builder().lgaName("Ndokwa East").stateCode("DE").lgaCode("DE011").build());
        lgas.add(Lgas.builder().lgaName("Ndokwa West").stateCode("DE").lgaCode("DE012").build());
        lgas.add(Lgas.builder().lgaName("Okpe").stateCode("DE").lgaCode("DE013").build());
        lgas.add(Lgas.builder().lgaName("Oshimili North").stateCode("DE").lgaCode("DE014").build());
        lgas.add(Lgas.builder().lgaName("Oshimili South").stateCode("DE").lgaCode("DE015").build());
        lgas.add(Lgas.builder().lgaName("Patani").stateCode("DE").lgaCode("DE016").build());
        lgas.add(Lgas.builder().lgaName("Sapele").stateCode("DE").lgaCode("DE017").build());
        lgas.add(Lgas.builder().lgaName("Udu").stateCode("DE").lgaCode("DE018").build());
        lgas.add(Lgas.builder().lgaName("Ughelli North").stateCode("DE").lgaCode("DE019").build());
        lgas.add(Lgas.builder().lgaName("Ughelli South").stateCode("DE").lgaCode("DE020").build());
        lgas.add(Lgas.builder().lgaName("Ukwuani").stateCode("DE").lgaCode("DE021").build());
        lgas.add(Lgas.builder().lgaName("Uvwie").stateCode("DE").lgaCode("DE022").build());
        lgas.add(Lgas.builder().lgaName("Warri North").stateCode("DE").lgaCode("DE023").build());
        lgas.add(Lgas.builder().lgaName("Warri South").stateCode("DE").lgaCode("DE024").build());
        lgas.add(Lgas.builder().lgaName("Warri South West").stateCode("DE").lgaCode("DE025").build());
        lgas.add(Lgas.builder().lgaName("DEXXXX").stateCode("DE").lgaCode("DEXXX").build());
        lgas.add(Lgas.builder().lgaName("Abakaliki").stateCode("EB").lgaCode("EB001").build());
        lgas.add(Lgas.builder().lgaName("Afikpo North").stateCode("EB").lgaCode("EB002").build());
        lgas.add(Lgas.builder().lgaName("Afikpo South").stateCode("EB").lgaCode("EB003").build());
        lgas.add(Lgas.builder().lgaName("Ebonyi").stateCode("EB").lgaCode("EB004").build());
        lgas.add(Lgas.builder().lgaName("Ezza North").stateCode("EB").lgaCode("EB005").build());
        lgas.add(Lgas.builder().lgaName("Ezza South").stateCode("EB").lgaCode("EB006").build());
        lgas.add(Lgas.builder().lgaName("Ikwo").stateCode("EB").lgaCode("EB007").build());
        lgas.add(Lgas.builder().lgaName("Ishielu").stateCode("EB").lgaCode("EB008").build());
        lgas.add(Lgas.builder().lgaName("Ivo").stateCode("EB").lgaCode("EB009").build());
        lgas.add(Lgas.builder().lgaName("Izzi").stateCode("EB").lgaCode("EB010").build());
        lgas.add(Lgas.builder().lgaName("Ohaozara").stateCode("EB").lgaCode("EB011").build());
        lgas.add(Lgas.builder().lgaName("Ohaukwu").stateCode("EB").lgaCode("EB012").build());
        lgas.add(Lgas.builder().lgaName("Onicha").stateCode("EB").lgaCode("EB013").build());
        lgas.add(Lgas.builder().lgaName("EBXXXX").stateCode("EB").lgaCode("EBXXX").build());
        lgas.add(Lgas.builder().lgaName("Akoko-Edo").stateCode("ED").lgaCode("ED001").build());
        lgas.add(Lgas.builder().lgaName("Egor").stateCode("ED").lgaCode("ED002").build());
        lgas.add(Lgas.builder().lgaName("Esan Central").stateCode("ED").lgaCode("ED003").build());
        lgas.add(Lgas.builder().lgaName("Esan North-East").stateCode("ED").lgaCode("ED004").build());
        lgas.add(Lgas.builder().lgaName("Esan South-East").stateCode("ED").lgaCode("ED005").build());
        lgas.add(Lgas.builder().lgaName("Esan West").stateCode("ED").lgaCode("ED006").build());
        lgas.add(Lgas.builder().lgaName("Etsako Central").stateCode("ED").lgaCode("ED007").build());
        lgas.add(Lgas.builder().lgaName("Etsako East").stateCode("ED").lgaCode("ED008").build());
        lgas.add(Lgas.builder().lgaName("Etsako West").stateCode("ED").lgaCode("ED009").build());
        lgas.add(Lgas.builder().lgaName("Igueben").stateCode("ED").lgaCode("ED010").build());
        lgas.add(Lgas.builder().lgaName("Ikpoba Okha").stateCode("ED").lgaCode("ED011").build());
        lgas.add(Lgas.builder().lgaName("Oredo").stateCode("ED").lgaCode("ED012").build());
        lgas.add(Lgas.builder().lgaName("Orhionmwon").stateCode("ED").lgaCode("ED013").build());
        lgas.add(Lgas.builder().lgaName("Ovia North-East").stateCode("ED").lgaCode("ED014").build());
        lgas.add(Lgas.builder().lgaName("Ovia South-West").stateCode("ED").lgaCode("ED015").build());
        lgas.add(Lgas.builder().lgaName("Owan East").stateCode("ED").lgaCode("ED016").build());
        lgas.add(Lgas.builder().lgaName("Owan West").stateCode("ED").lgaCode("ED017").build());
        lgas.add(Lgas.builder().lgaName("Uhunmwonde").stateCode("ED").lgaCode("ED018").build());
        lgas.add(Lgas.builder().lgaName("EDXXXX").stateCode("ED").lgaCode("EDXXX").build());
        lgas.add(Lgas.builder().lgaName("Ado Ekiti").stateCode("EK").lgaCode("EK001").build());
        lgas.add(Lgas.builder().lgaName("Efon").stateCode("EK").lgaCode("EK002").build());
        lgas.add(Lgas.builder().lgaName("Ekiti East").stateCode("EK").lgaCode("EK003").build());
        lgas.add(Lgas.builder().lgaName("Ekiti South-West").stateCode("EK").lgaCode("EK004").build());
        lgas.add(Lgas.builder().lgaName("Ekiti West").stateCode("EK").lgaCode("EK005").build());
        lgas.add(Lgas.builder().lgaName("Emure").stateCode("EK").lgaCode("EK006").build());
        lgas.add(Lgas.builder().lgaName("Gbonyin").stateCode("EK").lgaCode("EK007").build());
        lgas.add(Lgas.builder().lgaName("Ido Osi").stateCode("EK").lgaCode("EK008").build());
        lgas.add(Lgas.builder().lgaName("Ijero").stateCode("EK").lgaCode("EK009").build());
        lgas.add(Lgas.builder().lgaName("Ikere").stateCode("EK").lgaCode("EK010").build());
        lgas.add(Lgas.builder().lgaName("Ikole").stateCode("EK").lgaCode("EK011").build());
        lgas.add(Lgas.builder().lgaName("Ilejemeje").stateCode("EK").lgaCode("EK012").build());
        lgas.add(Lgas.builder().lgaName("Irepodun/Ifelodun").stateCode("EK").lgaCode("EK013").build());
        lgas.add(Lgas.builder().lgaName("Ise/Orun").stateCode("EK").lgaCode("EK014").build());
        lgas.add(Lgas.builder().lgaName("Moba").stateCode("EK").lgaCode("EK015").build());
        lgas.add(Lgas.builder().lgaName("Oye").stateCode("EK").lgaCode("EK016").build());
        lgas.add(Lgas.builder().lgaName("EKXXXX").stateCode("EK").lgaCode("EKXXX").build());
        lgas.add(Lgas.builder().lgaName("Aninri").stateCode("EN").lgaCode("EN001").build());
        lgas.add(Lgas.builder().lgaName("Awgu").stateCode("EN").lgaCode("EN002").build());
        lgas.add(Lgas.builder().lgaName("Enugu East").stateCode("EN").lgaCode("EN003").build());
        lgas.add(Lgas.builder().lgaName("Enugu North").stateCode("EN").lgaCode("EN004").build());
        lgas.add(Lgas.builder().lgaName("Enugu South").stateCode("EN").lgaCode("EN005").build());
        lgas.add(Lgas.builder().lgaName("Ezeagu").stateCode("EN").lgaCode("EN006").build());
        lgas.add(Lgas.builder().lgaName("Igbo Etiti").stateCode("EN").lgaCode("EN007").build());
        lgas.add(Lgas.builder().lgaName("Igbo Eze North").stateCode("EN").lgaCode("EN008").build());
        lgas.add(Lgas.builder().lgaName("Igbo Eze South").stateCode("EN").lgaCode("EN009").build());
        lgas.add(Lgas.builder().lgaName("Isi Uzo").stateCode("EN").lgaCode("EN010").build());
        lgas.add(Lgas.builder().lgaName("Nkanu East").stateCode("EN").lgaCode("EN011").build());
        lgas.add(Lgas.builder().lgaName("Nkanu West").stateCode("EN").lgaCode("EN012").build());
        lgas.add(Lgas.builder().lgaName("Nsukka").stateCode("EN").lgaCode("EN013").build());
        lgas.add(Lgas.builder().lgaName("Oji River").stateCode("EN").lgaCode("EN014").build());
        lgas.add(Lgas.builder().lgaName("Udenu").stateCode("EN").lgaCode("EN015").build());
        lgas.add(Lgas.builder().lgaName("Udi").stateCode("EN").lgaCode("EN016").build());
        lgas.add(Lgas.builder().lgaName("Uzo Uwani").stateCode("EN").lgaCode("EN017").build());
        lgas.add(Lgas.builder().lgaName("ENXXXX").stateCode("EN").lgaCode("ENXXX").build());
        lgas.add(Lgas.builder().lgaName("Abaji").stateCode("FC").lgaCode("FC001").build());
        lgas.add(Lgas.builder().lgaName("Bwari").stateCode("FC").lgaCode("FC002").build());
        lgas.add(Lgas.builder().lgaName("Gwagwalada").stateCode("FC").lgaCode("FC003").build());
        lgas.add(Lgas.builder().lgaName("Kuje").stateCode("FC").lgaCode("FC004").build());
        lgas.add(Lgas.builder().lgaName("Kwali").stateCode("FC").lgaCode("FC005").build());
        lgas.add(Lgas.builder().lgaName("Municipal Area Council").stateCode("FC").lgaCode("FC006").build());
        lgas.add(Lgas.builder().lgaName("FCXXXX").stateCode("FC").lgaCode("FCXXX").build());
        lgas.add(Lgas.builder().lgaName("Akko").stateCode("GO").lgaCode("GO001").build());
        lgas.add(Lgas.builder().lgaName("Balanga").stateCode("GO").lgaCode("GO002").build());
        lgas.add(Lgas.builder().lgaName("Billiri").stateCode("GO").lgaCode("GO003").build());
        lgas.add(Lgas.builder().lgaName("Dukku").stateCode("GO").lgaCode("GO004").build());
        lgas.add(Lgas.builder().lgaName("Funakaye").stateCode("GO").lgaCode("GO005").build());
        lgas.add(Lgas.builder().lgaName("Gombe").stateCode("GO").lgaCode("GO006").build());
        lgas.add(Lgas.builder().lgaName("Kaltungo").stateCode("GO").lgaCode("GO007").build());
        lgas.add(Lgas.builder().lgaName("Kwami").stateCode("GO").lgaCode("GO008").build());
        lgas.add(Lgas.builder().lgaName("Nafada").stateCode("GO").lgaCode("GO009").build());
        lgas.add(Lgas.builder().lgaName("Shongom").stateCode("GO").lgaCode("GO010").build());
        lgas.add(Lgas.builder().lgaName("Yamaltu/Deba").stateCode("GO").lgaCode("GO011").build());
        lgas.add(Lgas.builder().lgaName("GOXXXX").stateCode("GO").lgaCode("GOXXX").build());
        lgas.add(Lgas.builder().lgaName("Aboh Mbaise").stateCode("IM").lgaCode("IM001").build());
        lgas.add(Lgas.builder().lgaName("Ahiazu Mbaise").stateCode("IM").lgaCode("IM002").build());
        lgas.add(Lgas.builder().lgaName("Ehime Mbano").stateCode("IM").lgaCode("IM003").build());
        lgas.add(Lgas.builder().lgaName("Ezinihitte").stateCode("IM").lgaCode("IM004").build());
        lgas.add(Lgas.builder().lgaName("Ideato North").stateCode("IM").lgaCode("IM005").build());
        lgas.add(Lgas.builder().lgaName("Ideato South").stateCode("IM").lgaCode("IM006").build());
        lgas.add(Lgas.builder().lgaName("Ihitte/Uboma").stateCode("IM").lgaCode("IM007").build());
        lgas.add(Lgas.builder().lgaName("Ikeduru").stateCode("IM").lgaCode("IM008").build());
        lgas.add(Lgas.builder().lgaName("Isiala Mbano").stateCode("IM").lgaCode("IM009").build());
        lgas.add(Lgas.builder().lgaName("Isu").stateCode("IM").lgaCode("IM010").build());
        lgas.add(Lgas.builder().lgaName("Mbaitoli").stateCode("IM").lgaCode("IM011").build());
        lgas.add(Lgas.builder().lgaName("Ngor Okpala").stateCode("IM").lgaCode("IM012").build());
        lgas.add(Lgas.builder().lgaName("Njaba").stateCode("IM").lgaCode("IM013").build());
        lgas.add(Lgas.builder().lgaName("Nkwerre").stateCode("IM").lgaCode("IM014").build());
        lgas.add(Lgas.builder().lgaName("Nwangele").stateCode("IM").lgaCode("IM015").build());
        lgas.add(Lgas.builder().lgaName("Obowo").stateCode("IM").lgaCode("IM016").build());
        lgas.add(Lgas.builder().lgaName("Oguta").stateCode("IM").lgaCode("IM017").build());
        lgas.add(Lgas.builder().lgaName("Ohaji/Egbema").stateCode("IM").lgaCode("IM018").build());
        lgas.add(Lgas.builder().lgaName("Okigwe").stateCode("IM").lgaCode("IM019").build());
        lgas.add(Lgas.builder().lgaName("Unuimo").stateCode("IM").lgaCode("IM020").build());
        lgas.add(Lgas.builder().lgaName("Orlu").stateCode("IM").lgaCode("IM021").build());
        lgas.add(Lgas.builder().lgaName("Orsu").stateCode("IM").lgaCode("IM022").build());
        lgas.add(Lgas.builder().lgaName("Oru East").stateCode("IM").lgaCode("IM023").build());
        lgas.add(Lgas.builder().lgaName("Oru West").stateCode("IM").lgaCode("IM024").build());
        lgas.add(Lgas.builder().lgaName("Owerri Municipal").stateCode("IM").lgaCode("IM025").build());
        lgas.add(Lgas.builder().lgaName("Owerri North").stateCode("IM").lgaCode("IM026").build());
        lgas.add(Lgas.builder().lgaName("Owerri West").stateCode("IM").lgaCode("IM027").build());
        lgas.add(Lgas.builder().lgaName("IMXXXX").stateCode("IM").lgaCode("IMXXX").build());
        lgas.add(Lgas.builder().lgaName("Auyo").stateCode("JI").lgaCode("JI001").build());
        lgas.add(Lgas.builder().lgaName("Babura").stateCode("JI").lgaCode("JI002").build());
        lgas.add(Lgas.builder().lgaName("Biriniwa").stateCode("JI").lgaCode("JI003").build());
        lgas.add(Lgas.builder().lgaName("Birnin Kudu").stateCode("JI").lgaCode("JI004").build());
        lgas.add(Lgas.builder().lgaName("Buji").stateCode("JI").lgaCode("JI005").build());
        lgas.add(Lgas.builder().lgaName("Dutse").stateCode("JI").lgaCode("JI006").build());
        lgas.add(Lgas.builder().lgaName("Gagarawa").stateCode("JI").lgaCode("JI007").build());
        lgas.add(Lgas.builder().lgaName("Garki").stateCode("JI").lgaCode("JI008").build());
        lgas.add(Lgas.builder().lgaName("Gumel").stateCode("JI").lgaCode("JI009").build());
        lgas.add(Lgas.builder().lgaName("Guri").stateCode("JI").lgaCode("JI010").build());
        lgas.add(Lgas.builder().lgaName("Gwaram").stateCode("JI").lgaCode("JI011").build());
        lgas.add(Lgas.builder().lgaName("Gwiwa").stateCode("JI").lgaCode("JI012").build());
        lgas.add(Lgas.builder().lgaName("Hadejia").stateCode("JI").lgaCode("JI013").build());
        lgas.add(Lgas.builder().lgaName("Jahun").stateCode("JI").lgaCode("JI014").build());
        lgas.add(Lgas.builder().lgaName("Kafin Hausa").stateCode("JI").lgaCode("JI015").build());
        lgas.add(Lgas.builder().lgaName("Kaugama").stateCode("JI").lgaCode("JI016").build());
        lgas.add(Lgas.builder().lgaName("Kazaure").stateCode("JI").lgaCode("JI017").build());
        lgas.add(Lgas.builder().lgaName("Kiri Kasama").stateCode("JI").lgaCode("JI018").build());
        lgas.add(Lgas.builder().lgaName("Kiyawa").stateCode("JI").lgaCode("JI019").build());
        lgas.add(Lgas.builder().lgaName("Maigatari").stateCode("JI").lgaCode("JI020").build());
        lgas.add(Lgas.builder().lgaName("Malam Madori").stateCode("JI").lgaCode("JI021").build());
        lgas.add(Lgas.builder().lgaName("Miga").stateCode("JI").lgaCode("JI022").build());
        lgas.add(Lgas.builder().lgaName("Ringim").stateCode("JI").lgaCode("JI023").build());
        lgas.add(Lgas.builder().lgaName("Roni").stateCode("JI").lgaCode("JI024").build());
        lgas.add(Lgas.builder().lgaName("Sule Tankarkar").stateCode("JI").lgaCode("JI025").build());
        lgas.add(Lgas.builder().lgaName("Taura").stateCode("JI").lgaCode("JI026").build());
        lgas.add(Lgas.builder().lgaName("Yankwashi").stateCode("JI").lgaCode("JI027").build());
        lgas.add(Lgas.builder().lgaName("JIXXXX").stateCode("JI").lgaCode("JIXXX").build());
        lgas.add(Lgas.builder().lgaName("Birnin Gwari").stateCode("KD").lgaCode("KD001").build());
        lgas.add(Lgas.builder().lgaName("Chikun").stateCode("KD").lgaCode("KD002").build());
        lgas.add(Lgas.builder().lgaName("Giwa").stateCode("KD").lgaCode("KD003").build());
        lgas.add(Lgas.builder().lgaName("Igabi").stateCode("KD").lgaCode("KD004").build());
        lgas.add(Lgas.builder().lgaName("Ikara").stateCode("KD").lgaCode("KD005").build());
        lgas.add(Lgas.builder().lgaName("Jaba").stateCode("KD").lgaCode("KD006").build());
        lgas.add(Lgas.builder().lgaName("Jemaa").stateCode("KD").lgaCode("KD007").build());
        lgas.add(Lgas.builder().lgaName("Kachia").stateCode("KD").lgaCode("KD008").build());
        lgas.add(Lgas.builder().lgaName("Kaduna North").stateCode("KD").lgaCode("KD009").build());
        lgas.add(Lgas.builder().lgaName("Kaduna South").stateCode("KD").lgaCode("KD010").build());
        lgas.add(Lgas.builder().lgaName("Kagarko").stateCode("KD").lgaCode("KD011").build());
        lgas.add(Lgas.builder().lgaName("Kajuru").stateCode("KD").lgaCode("KD012").build());
        lgas.add(Lgas.builder().lgaName("Kaura").stateCode("KD").lgaCode("KD013").build());
        lgas.add(Lgas.builder().lgaName("Kauru").stateCode("KD").lgaCode("KD014").build());
        lgas.add(Lgas.builder().lgaName("Kubau").stateCode("KD").lgaCode("KD015").build());
        lgas.add(Lgas.builder().lgaName("Kudan").stateCode("KD").lgaCode("KD016").build());
        lgas.add(Lgas.builder().lgaName("Lere").stateCode("KD").lgaCode("KD017").build());
        lgas.add(Lgas.builder().lgaName("Makarfi").stateCode("KD").lgaCode("KD018").build());
        lgas.add(Lgas.builder().lgaName("Sabon Gari").stateCode("KD").lgaCode("KD019").build());
        lgas.add(Lgas.builder().lgaName("Sanga").stateCode("KD").lgaCode("KD020").build());
        lgas.add(Lgas.builder().lgaName("Soba").stateCode("KD").lgaCode("KD021").build());
        lgas.add(Lgas.builder().lgaName("Zangon Kataf").stateCode("KD").lgaCode("KD022").build());
        lgas.add(Lgas.builder().lgaName("Zaria").stateCode("KD").lgaCode("KD023").build());
        lgas.add(Lgas.builder().lgaName("KDXXXX").stateCode("KD").lgaCode("KDXXX").build());
        lgas.add(Lgas.builder().lgaName("Aleiro").stateCode("KE").lgaCode("KE001").build());
        lgas.add(Lgas.builder().lgaName("Arewa Dandi").stateCode("KE").lgaCode("KE002").build());
        lgas.add(Lgas.builder().lgaName("Argungu").stateCode("KE").lgaCode("KE003").build());
        lgas.add(Lgas.builder().lgaName("Augie").stateCode("KE").lgaCode("KE004").build());
        lgas.add(Lgas.builder().lgaName("Bagudo").stateCode("KE").lgaCode("KE005").build());
        lgas.add(Lgas.builder().lgaName("Birnin Kebbi").stateCode("KE").lgaCode("KE006").build());
        lgas.add(Lgas.builder().lgaName("Bunza").stateCode("KE").lgaCode("KE007").build());
        lgas.add(Lgas.builder().lgaName("Dandi").stateCode("KE").lgaCode("KE008").build());
        lgas.add(Lgas.builder().lgaName("Fakai").stateCode("KE").lgaCode("KE009").build());
        lgas.add(Lgas.builder().lgaName("Gwandu").stateCode("KE").lgaCode("KE010").build());
        lgas.add(Lgas.builder().lgaName("Jega").stateCode("KE").lgaCode("KE011").build());
        lgas.add(Lgas.builder().lgaName("Kalgo").stateCode("KE").lgaCode("KE012").build());
        lgas.add(Lgas.builder().lgaName("Koko/Besse").stateCode("KE").lgaCode("KE013").build());
        lgas.add(Lgas.builder().lgaName("Maiyama").stateCode("KE").lgaCode("KE014").build());
        lgas.add(Lgas.builder().lgaName("Ngaski").stateCode("KE").lgaCode("KE015").build());
        lgas.add(Lgas.builder().lgaName("Sakaba").stateCode("KE").lgaCode("KE016").build());
        lgas.add(Lgas.builder().lgaName("Shanga").stateCode("KE").lgaCode("KE017").build());
        lgas.add(Lgas.builder().lgaName("Suru").stateCode("KE").lgaCode("KE018").build());
        lgas.add(Lgas.builder().lgaName("Wasagu/Danko").stateCode("KE").lgaCode("KE019").build());
        lgas.add(Lgas.builder().lgaName("Yauri").stateCode("KE").lgaCode("KE020").build());
        lgas.add(Lgas.builder().lgaName("Zuru").stateCode("KE").lgaCode("KE021").build());
        lgas.add(Lgas.builder().lgaName("KEXXXX").stateCode("KE").lgaCode("KEXXX").build());
        lgas.add(Lgas.builder().lgaName("Ajingi").stateCode("KN").lgaCode("KN001").build());
        lgas.add(Lgas.builder().lgaName("Albasu").stateCode("KN").lgaCode("KN002").build());
        lgas.add(Lgas.builder().lgaName("Bagwai").stateCode("KN").lgaCode("KN003").build());
        lgas.add(Lgas.builder().lgaName("Bebeji").stateCode("KN").lgaCode("KN004").build());
        lgas.add(Lgas.builder().lgaName("Bichi").stateCode("KN").lgaCode("KN005").build());
        lgas.add(Lgas.builder().lgaName("Bunkure").stateCode("KN").lgaCode("KN006").build());
        lgas.add(Lgas.builder().lgaName("Dala").stateCode("KN").lgaCode("KN007").build());
        lgas.add(Lgas.builder().lgaName("Dambatta").stateCode("KN").lgaCode("KN008").build());
        lgas.add(Lgas.builder().lgaName("Dawakin Kudu").stateCode("KN").lgaCode("KN009").build());
        lgas.add(Lgas.builder().lgaName("Dawakin Tofa").stateCode("KN").lgaCode("KN010").build());
        lgas.add(Lgas.builder().lgaName("Doguwa").stateCode("KN").lgaCode("KN011").build());
        lgas.add(Lgas.builder().lgaName("Fagge").stateCode("KN").lgaCode("KN012").build());
        lgas.add(Lgas.builder().lgaName("Gabasawa").stateCode("KN").lgaCode("KN013").build());
        lgas.add(Lgas.builder().lgaName("Garko").stateCode("KN").lgaCode("KN014").build());
        lgas.add(Lgas.builder().lgaName("Garun Mallam").stateCode("KN").lgaCode("KN015").build());
        lgas.add(Lgas.builder().lgaName("Gaya").stateCode("KN").lgaCode("KN016").build());
        lgas.add(Lgas.builder().lgaName("Gezawa").stateCode("KN").lgaCode("KN017").build());
        lgas.add(Lgas.builder().lgaName("Gwale").stateCode("KN").lgaCode("KN018").build());
        lgas.add(Lgas.builder().lgaName("Gwarzo").stateCode("KN").lgaCode("KN019").build());
        lgas.add(Lgas.builder().lgaName("Kabo").stateCode("KN").lgaCode("KN020").build());
        lgas.add(Lgas.builder().lgaName("Kano Municipal").stateCode("KN").lgaCode("KN021").build());
        lgas.add(Lgas.builder().lgaName("Karaye").stateCode("KN").lgaCode("KN022").build());
        lgas.add(Lgas.builder().lgaName("Kibiya").stateCode("KN").lgaCode("KN023").build());
        lgas.add(Lgas.builder().lgaName("Kiru").stateCode("KN").lgaCode("KN024").build());
        lgas.add(Lgas.builder().lgaName("Kumbotso").stateCode("KN").lgaCode("KN025").build());
        lgas.add(Lgas.builder().lgaName("Kunchi").stateCode("KN").lgaCode("KN026").build());
        lgas.add(Lgas.builder().lgaName("Kura").stateCode("KN").lgaCode("KN027").build());
        lgas.add(Lgas.builder().lgaName("Madobi").stateCode("KN").lgaCode("KN028").build());
        lgas.add(Lgas.builder().lgaName("Makoda").stateCode("KN").lgaCode("KN029").build());
        lgas.add(Lgas.builder().lgaName("Minjibir").stateCode("KN").lgaCode("KN030").build());
        lgas.add(Lgas.builder().lgaName("Nasarawa").stateCode("KN").lgaCode("KN031").build());
        lgas.add(Lgas.builder().lgaName("Rano").stateCode("KN").lgaCode("KN032").build());
        lgas.add(Lgas.builder().lgaName("Rimin Gado").stateCode("KN").lgaCode("KN033").build());
        lgas.add(Lgas.builder().lgaName("Rogo").stateCode("KN").lgaCode("KN034").build());
        lgas.add(Lgas.builder().lgaName("Shanono").stateCode("KN").lgaCode("KN035").build());
        lgas.add(Lgas.builder().lgaName("Sumaila").stateCode("KN").lgaCode("KN036").build());
        lgas.add(Lgas.builder().lgaName("Takai").stateCode("KN").lgaCode("KN037").build());
        lgas.add(Lgas.builder().lgaName("Tarauni").stateCode("KN").lgaCode("KN038").build());
        lgas.add(Lgas.builder().lgaName("Tofa").stateCode("KN").lgaCode("KN039").build());
        lgas.add(Lgas.builder().lgaName("Tsanyawa").stateCode("KN").lgaCode("KN040").build());
        lgas.add(Lgas.builder().lgaName("Tudun Wada").stateCode("KN").lgaCode("KN041").build());
        lgas.add(Lgas.builder().lgaName("Ungogo").stateCode("KN").lgaCode("KN042").build());
        lgas.add(Lgas.builder().lgaName("Warawa").stateCode("KN").lgaCode("KN043").build());
        lgas.add(Lgas.builder().lgaName("Wudil").stateCode("KN").lgaCode("KN044").build());
        lgas.add(Lgas.builder().lgaName("KNXXXX").stateCode("KN").lgaCode("KNXXX").build());
        lgas.add(Lgas.builder().lgaName("Adavi").stateCode("KO").lgaCode("KO001").build());
        lgas.add(Lgas.builder().lgaName("Ajaokuta").stateCode("KO").lgaCode("KO002").build());
        lgas.add(Lgas.builder().lgaName("Ankpa").stateCode("KO").lgaCode("KO003").build());
        lgas.add(Lgas.builder().lgaName("Bassa").stateCode("KO").lgaCode("KO004").build());
        lgas.add(Lgas.builder().lgaName("Dekina").stateCode("KO").lgaCode("KO005").build());
        lgas.add(Lgas.builder().lgaName("Ibaji").stateCode("KO").lgaCode("KO006").build());
        lgas.add(Lgas.builder().lgaName("Idah").stateCode("KO").lgaCode("KO007").build());
        lgas.add(Lgas.builder().lgaName("Igalamela Odolu").stateCode("KO").lgaCode("KO008").build());
        lgas.add(Lgas.builder().lgaName("Ijumu").stateCode("KO").lgaCode("KO009").build());
        lgas.add(Lgas.builder().lgaName("Kabba/Bunu").stateCode("KO").lgaCode("KO010").build());
        lgas.add(Lgas.builder().lgaName("Kogi").stateCode("KO").lgaCode("KO011").build());
        lgas.add(Lgas.builder().lgaName("Lokoja").stateCode("KO").lgaCode("KO012").build());
        lgas.add(Lgas.builder().lgaName("Mopa Muro").stateCode("KO").lgaCode("KO013").build());
        lgas.add(Lgas.builder().lgaName("Ofu").stateCode("KO").lgaCode("KO014").build());
        lgas.add(Lgas.builder().lgaName("Ogori/Magongo").stateCode("KO").lgaCode("KO015").build());
        lgas.add(Lgas.builder().lgaName("Okehi").stateCode("KO").lgaCode("KO016").build());
        lgas.add(Lgas.builder().lgaName("Okene").stateCode("KO").lgaCode("KO017").build());
        lgas.add(Lgas.builder().lgaName("Olamaboro").stateCode("KO").lgaCode("KO018").build());
        lgas.add(Lgas.builder().lgaName("Omala").stateCode("KO").lgaCode("KO019").build());
        lgas.add(Lgas.builder().lgaName("Yagba East").stateCode("KO").lgaCode("KO020").build());
        lgas.add(Lgas.builder().lgaName("Yagba West").stateCode("KO").lgaCode("KO021").build());
        lgas.add(Lgas.builder().lgaName("KOXXXX").stateCode("KO").lgaCode("KOXXX").build());
        lgas.add(Lgas.builder().lgaName("Bakori").stateCode("KT").lgaCode("KT001").build());
        lgas.add(Lgas.builder().lgaName("Batagarawa").stateCode("KT").lgaCode("KT002").build());
        lgas.add(Lgas.builder().lgaName("Batsari").stateCode("KT").lgaCode("KT003").build());
        lgas.add(Lgas.builder().lgaName("Baure").stateCode("KT").lgaCode("KT004").build());
        lgas.add(Lgas.builder().lgaName("Bindawa").stateCode("KT").lgaCode("KT005").build());
        lgas.add(Lgas.builder().lgaName("Charanchi").stateCode("KT").lgaCode("KT006").build());
        lgas.add(Lgas.builder().lgaName("Dan Musa").stateCode("KT").lgaCode("KT007").build());
        lgas.add(Lgas.builder().lgaName("Dandume").stateCode("KT").lgaCode("KT008").build());
        lgas.add(Lgas.builder().lgaName("Danja").stateCode("KT").lgaCode("KT009").build());
        lgas.add(Lgas.builder().lgaName("Daura").stateCode("KT").lgaCode("KT010").build());
        lgas.add(Lgas.builder().lgaName("Dutsi").stateCode("KT").lgaCode("KT011").build());
        lgas.add(Lgas.builder().lgaName("Dutsin Ma").stateCode("KT").lgaCode("KT012").build());
        lgas.add(Lgas.builder().lgaName("Faskari").stateCode("KT").lgaCode("KT013").build());
        lgas.add(Lgas.builder().lgaName("Funtua").stateCode("KT").lgaCode("KT014").build());
        lgas.add(Lgas.builder().lgaName("Ingawa").stateCode("KT").lgaCode("KT015").build());
        lgas.add(Lgas.builder().lgaName("Jibia").stateCode("KT").lgaCode("KT016").build());
        lgas.add(Lgas.builder().lgaName("Kafur").stateCode("KT").lgaCode("KT017").build());
        lgas.add(Lgas.builder().lgaName("Kaita").stateCode("KT").lgaCode("KT018").build());
        lgas.add(Lgas.builder().lgaName("Kankara").stateCode("KT").lgaCode("KT019").build());
        lgas.add(Lgas.builder().lgaName("Kankia").stateCode("KT").lgaCode("KT020").build());
        lgas.add(Lgas.builder().lgaName("Katsina").stateCode("KT").lgaCode("KT021").build());
        lgas.add(Lgas.builder().lgaName("Kurfi").stateCode("KT").lgaCode("KT022").build());
        lgas.add(Lgas.builder().lgaName("Kusada").stateCode("KT").lgaCode("KT023").build());
        lgas.add(Lgas.builder().lgaName("Mai Adua").stateCode("KT").lgaCode("KT024").build());
        lgas.add(Lgas.builder().lgaName("Malumfashi").stateCode("KT").lgaCode("KT025").build());
        lgas.add(Lgas.builder().lgaName("Mani").stateCode("KT").lgaCode("KT026").build());
        lgas.add(Lgas.builder().lgaName("Mashi").stateCode("KT").lgaCode("KT027").build());
        lgas.add(Lgas.builder().lgaName("Matazu").stateCode("KT").lgaCode("KT028").build());
        lgas.add(Lgas.builder().lgaName("Musawa").stateCode("KT").lgaCode("KT029").build());
        lgas.add(Lgas.builder().lgaName("Rimi").stateCode("KT").lgaCode("KT030").build());
        lgas.add(Lgas.builder().lgaName("Sabuwa").stateCode("KT").lgaCode("KT031").build());
        lgas.add(Lgas.builder().lgaName("Safana").stateCode("KT").lgaCode("KT032").build());
        lgas.add(Lgas.builder().lgaName("Sandamu").stateCode("KT").lgaCode("KT033").build());
        lgas.add(Lgas.builder().lgaName("Zango").stateCode("KT").lgaCode("KT034").build());
        lgas.add(Lgas.builder().lgaName("KTXXXX").stateCode("KT").lgaCode("KTXXX").build());
        lgas.add(Lgas.builder().lgaName("Asa").stateCode("KW").lgaCode("KW001").build());
        lgas.add(Lgas.builder().lgaName("Baruten").stateCode("KW").lgaCode("KW002").build());
        lgas.add(Lgas.builder().lgaName("Edu").stateCode("KW").lgaCode("KW003").build());
        lgas.add(Lgas.builder().lgaName("Ekiti").stateCode("KW").lgaCode("KW004").build());
        lgas.add(Lgas.builder().lgaName("Ifelodun").stateCode("KW").lgaCode("KW005").build());
        lgas.add(Lgas.builder().lgaName("Ilorin East").stateCode("KW").lgaCode("KW006").build());
        lgas.add(Lgas.builder().lgaName("Ilorin South").stateCode("KW").lgaCode("KW007").build());
        lgas.add(Lgas.builder().lgaName("Ilorin West").stateCode("KW").lgaCode("KW008").build());
        lgas.add(Lgas.builder().lgaName("Irepodun").stateCode("KW").lgaCode("KW009").build());
        lgas.add(Lgas.builder().lgaName("Isin").stateCode("KW").lgaCode("KW010").build());
        lgas.add(Lgas.builder().lgaName("Kaiama").stateCode("KW").lgaCode("KW011").build());
        lgas.add(Lgas.builder().lgaName("Moro").stateCode("KW").lgaCode("KW012").build());
        lgas.add(Lgas.builder().lgaName("Offa").stateCode("KW").lgaCode("KW013").build());
        lgas.add(Lgas.builder().lgaName("Oke Ero").stateCode("KW").lgaCode("KW014").build());
        lgas.add(Lgas.builder().lgaName("Oyun").stateCode("KW").lgaCode("KW015").build());
        lgas.add(Lgas.builder().lgaName("Pategi").stateCode("KW").lgaCode("KW016").build());
        lgas.add(Lgas.builder().lgaName("KWXXXX").stateCode("KW").lgaCode("KWXXX").build());
        lgas.add(Lgas.builder().lgaName("Epe").stateCode("LA").lgaCode("LA001").build());
        lgas.add(Lgas.builder().lgaName("Ibeju-Lekki").stateCode("LA").lgaCode("LA002").build());
        lgas.add(Lgas.builder().lgaName("Eti Osa").stateCode("LA").lgaCode("LA003").build());
        lgas.add(Lgas.builder().lgaName("Lagos Island").stateCode("LA").lgaCode("LA004").build());
        lgas.add(Lgas.builder().lgaName("Amuwo-Odofin").stateCode("LA").lgaCode("LA005").build());
        lgas.add(Lgas.builder().lgaName("Apapa").stateCode("LA").lgaCode("LA006").build());
        lgas.add(Lgas.builder().lgaName("Ajeromi-Ifelodun").stateCode("LA").lgaCode("LA007").build());
        lgas.add(Lgas.builder().lgaName("Badagry").stateCode("LA").lgaCode("LA008").build());
        lgas.add(Lgas.builder().lgaName("Ojo").stateCode("LA").lgaCode("LA009").build());
        lgas.add(Lgas.builder().lgaName("Oshodi-Isolo").stateCode("LA").lgaCode("LA010").build());
        lgas.add(Lgas.builder().lgaName("Alimosho").stateCode("LA").lgaCode("LA011").build());
        lgas.add(Lgas.builder().lgaName("Agege").stateCode("LA").lgaCode("LA012").build());
        lgas.add(Lgas.builder().lgaName("Ifako-Ijaiye").stateCode("LA").lgaCode("LA013").build());
        lgas.add(Lgas.builder().lgaName("Mushin").stateCode("LA").lgaCode("LA014").build());
        lgas.add(Lgas.builder().lgaName("Ikeja").stateCode("LA").lgaCode("LA015").build());
        lgas.add(Lgas.builder().lgaName("Surulere").stateCode("LA").lgaCode("LA016").build());
        lgas.add(Lgas.builder().lgaName("Shomolu").stateCode("LA").lgaCode("LA017").build());
        lgas.add(Lgas.builder().lgaName("Lagos Mainland").stateCode("LA").lgaCode("LA018").build());
        lgas.add(Lgas.builder().lgaName("Ikorodu").stateCode("LA").lgaCode("LA019").build());
        lgas.add(Lgas.builder().lgaName("Kosofe").stateCode("LA").lgaCode("LA020").build());
        lgas.add(Lgas.builder().lgaName("LAXXXX").stateCode("LA").lgaCode("LAXXX").build());
        lgas.add(Lgas.builder().lgaName("Akwanga").stateCode("NA").lgaCode("NA001").build());
        lgas.add(Lgas.builder().lgaName("Nasarawa Egon").stateCode("NA").lgaCode("NA002").build());
        lgas.add(Lgas.builder().lgaName("Wamba").stateCode("NA").lgaCode("NA003").build());
        lgas.add(Lgas.builder().lgaName("Karu").stateCode("NA").lgaCode("NA004").build());
        lgas.add(Lgas.builder().lgaName("Keffi").stateCode("NA").lgaCode("NA005").build());
        lgas.add(Lgas.builder().lgaName("Kokona").stateCode("NA").lgaCode("NA006").build());
        lgas.add(Lgas.builder().lgaName("Doma").stateCode("NA").lgaCode("NA007").build());
        lgas.add(Lgas.builder().lgaName("Lafia").stateCode("NA").lgaCode("NA008").build());
        lgas.add(Lgas.builder().lgaName("Nasarawa").stateCode("NA").lgaCode("NA009").build());
        lgas.add(Lgas.builder().lgaName("Toto").stateCode("NA").lgaCode("NA010").build());
        lgas.add(Lgas.builder().lgaName("Keana").stateCode("NA").lgaCode("NA011").build());
        lgas.add(Lgas.builder().lgaName("Awe").stateCode("NA").lgaCode("NA012").build());
        lgas.add(Lgas.builder().lgaName("Obi").stateCode("NA").lgaCode("NA013").build());
        lgas.add(Lgas.builder().lgaName("NAXXXX").stateCode("NA").lgaCode("NAXXX").build());
        lgas.add(Lgas.builder().lgaName("Agaie").stateCode("NI").lgaCode("NI001").build());
        lgas.add(Lgas.builder().lgaName("Agwara").stateCode("NI").lgaCode("NI002").build());
        lgas.add(Lgas.builder().lgaName("Bida").stateCode("NI").lgaCode("NI003").build());
        lgas.add(Lgas.builder().lgaName("Borgu").stateCode("NI").lgaCode("NI004").build());
        lgas.add(Lgas.builder().lgaName("Bosso").stateCode("NI").lgaCode("NI005").build());
        lgas.add(Lgas.builder().lgaName("Chanchaga").stateCode("NI").lgaCode("NI006").build());
        lgas.add(Lgas.builder().lgaName("Edati").stateCode("NI").lgaCode("NI007").build());
        lgas.add(Lgas.builder().lgaName("Gbako").stateCode("NI").lgaCode("NI008").build());
        lgas.add(Lgas.builder().lgaName("Gurara").stateCode("NI").lgaCode("NI009").build());
        lgas.add(Lgas.builder().lgaName("Katcha").stateCode("NI").lgaCode("NI010").build());
        lgas.add(Lgas.builder().lgaName("Kontagora").stateCode("NI").lgaCode("NI011").build());
        lgas.add(Lgas.builder().lgaName("Lapai").stateCode("NI").lgaCode("NI012").build());
        lgas.add(Lgas.builder().lgaName("Lavun").stateCode("NI").lgaCode("NI013").build());
        lgas.add(Lgas.builder().lgaName("Magama").stateCode("NI").lgaCode("NI014").build());
        lgas.add(Lgas.builder().lgaName("Mariga").stateCode("NI").lgaCode("NI015").build());
        lgas.add(Lgas.builder().lgaName("Mashegu").stateCode("NI").lgaCode("NI016").build());
        lgas.add(Lgas.builder().lgaName("Mokwa").stateCode("NI").lgaCode("NI017").build());
        lgas.add(Lgas.builder().lgaName("Moya").stateCode("NI").lgaCode("NI018").build());
        lgas.add(Lgas.builder().lgaName("Paikoro").stateCode("NI").lgaCode("NI019").build());
        lgas.add(Lgas.builder().lgaName("Rafi").stateCode("NI").lgaCode("NI020").build());
        lgas.add(Lgas.builder().lgaName("Rijau").stateCode("NI").lgaCode("NI021").build());
        lgas.add(Lgas.builder().lgaName("Shiroro").stateCode("NI").lgaCode("NI022").build());
        lgas.add(Lgas.builder().lgaName("Suleja").stateCode("NI").lgaCode("NI023").build());
        lgas.add(Lgas.builder().lgaName("Tafa").stateCode("NI").lgaCode("NI024").build());
        lgas.add(Lgas.builder().lgaName("Wushishi").stateCode("NI").lgaCode("NI025").build());
        lgas.add(Lgas.builder().lgaName("NIXXXX").stateCode("NI").lgaCode("NIXXX").build());
        lgas.add(Lgas.builder().lgaName("Imeko Afon").stateCode("OG").lgaCode("OG001").build());
        lgas.add(Lgas.builder().lgaName("Abeokuta South").stateCode("OG").lgaCode("OG002").build());
        lgas.add(Lgas.builder().lgaName("Abeokuta North").stateCode("OG").lgaCode("OG003").build());
        lgas.add(Lgas.builder().lgaName("Egbado North").stateCode("OG").lgaCode("OG004").build());
        lgas.add(Lgas.builder().lgaName("Egbado South").stateCode("OG").lgaCode("OG005").build());
        lgas.add(Lgas.builder().lgaName("Ikenne").stateCode("OG").lgaCode("OG006").build());
        lgas.add(Lgas.builder().lgaName("Shagamu").stateCode("OG").lgaCode("OG007").build());
        lgas.add(Lgas.builder().lgaName("Ipokia").stateCode("OG").lgaCode("OG008").build());
        lgas.add(Lgas.builder().lgaName("Ado-Odo/Ota").stateCode("OG").lgaCode("OG009").build());
        lgas.add(Lgas.builder().lgaName("Ewekoro").stateCode("OG").lgaCode("OG010").build());
        lgas.add(Lgas.builder().lgaName("Ifo").stateCode("OG").lgaCode("OG011").build());
        lgas.add(Lgas.builder().lgaName("Odeda").stateCode("OG").lgaCode("OG012").build());
        lgas.add(Lgas.builder().lgaName("Obafemi Owode").stateCode("OG").lgaCode("OG013").build());
        lgas.add(Lgas.builder().lgaName("Ogun Waterside").stateCode("OG").lgaCode("OG014").build());
        lgas.add(Lgas.builder().lgaName("Ijebu East").stateCode("OG").lgaCode("OG015").build());
        lgas.add(Lgas.builder().lgaName("Ijebu Ode").stateCode("OG").lgaCode("OG016").build());
        lgas.add(Lgas.builder().lgaName("Remo North").stateCode("OG").lgaCode("OG017").build());
        lgas.add(Lgas.builder().lgaName("Ijebu North").stateCode("OG").lgaCode("OG018").build());
        lgas.add(Lgas.builder().lgaName("Ijebu North East").stateCode("OG").lgaCode("OG019").build());
        lgas.add(Lgas.builder().lgaName("Odogbolu").stateCode("OG").lgaCode("OG020").build());
        lgas.add(Lgas.builder().lgaName("OGXXXX").stateCode("OG").lgaCode("OGXXX").build());
        lgas.add(Lgas.builder().lgaName("Ifedore").stateCode("ON").lgaCode("ON001").build());
        lgas.add(Lgas.builder().lgaName("Ile Oluji/Okeigbo").stateCode("ON").lgaCode("ON002").build());
        lgas.add(Lgas.builder().lgaName("Akure North").stateCode("ON").lgaCode("ON003").build());
        lgas.add(Lgas.builder().lgaName("Akure South").stateCode("ON").lgaCode("ON004").build());
        lgas.add(Lgas.builder().lgaName("Ose").stateCode("ON").lgaCode("ON005").build());
        lgas.add(Lgas.builder().lgaName("Owo").stateCode("ON").lgaCode("ON006").build());
        lgas.add(Lgas.builder().lgaName("Akoko North-West").stateCode("ON").lgaCode("ON007").build());
        lgas.add(Lgas.builder().lgaName("Akoko North-East").stateCode("ON").lgaCode("ON008").build());
        lgas.add(Lgas.builder().lgaName("Akoko South-East").stateCode("ON").lgaCode("ON009").build());
        lgas.add(Lgas.builder().lgaName("Akoko South-West").stateCode("ON").lgaCode("ON010").build());
        lgas.add(Lgas.builder().lgaName("Idanre").stateCode("ON").lgaCode("ON011").build());
        lgas.add(Lgas.builder().lgaName("Ondo East").stateCode("ON").lgaCode("ON012").build());
        lgas.add(Lgas.builder().lgaName("Ondo West").stateCode("ON").lgaCode("ON013").build());
        lgas.add(Lgas.builder().lgaName("Odigbo").stateCode("ON").lgaCode("ON014").build());
        lgas.add(Lgas.builder().lgaName("Ese Odo").stateCode("ON").lgaCode("ON015").build());
        lgas.add(Lgas.builder().lgaName("Ilaje").stateCode("ON").lgaCode("ON016").build());
        lgas.add(Lgas.builder().lgaName("Okitipupa").stateCode("ON").lgaCode("ON017").build());
        lgas.add(Lgas.builder().lgaName("Irele").stateCode("ON").lgaCode("ON018").build());
        lgas.add(Lgas.builder().lgaName("ONXXXX").stateCode("ON").lgaCode("ONXXX").build());
        lgas.add(Lgas.builder().lgaName("Aiyedaade").stateCode("OS").lgaCode("OS001").build());
        lgas.add(Lgas.builder().lgaName("Aiyedire").stateCode("OS").lgaCode("OS002").build());
        lgas.add(Lgas.builder().lgaName("Atakunmosa East").stateCode("OS").lgaCode("OS003").build());
        lgas.add(Lgas.builder().lgaName("Atakunmosa West").stateCode("OS").lgaCode("OS004").build());
        lgas.add(Lgas.builder().lgaName("Boluwaduro").stateCode("OS").lgaCode("OS005").build());
        lgas.add(Lgas.builder().lgaName("Boripe").stateCode("OS").lgaCode("OS006").build());
        lgas.add(Lgas.builder().lgaName("Ede North").stateCode("OS").lgaCode("OS007").build());
        lgas.add(Lgas.builder().lgaName("Ede South").stateCode("OS").lgaCode("OS008").build());
        lgas.add(Lgas.builder().lgaName("Egbedore").stateCode("OS").lgaCode("OS009").build());
        lgas.add(Lgas.builder().lgaName("Ejigbo").stateCode("OS").lgaCode("OS010").build());
        lgas.add(Lgas.builder().lgaName("Ife Central").stateCode("OS").lgaCode("OS011").build());
        lgas.add(Lgas.builder().lgaName("Ife East").stateCode("OS").lgaCode("OS012").build());
        lgas.add(Lgas.builder().lgaName("Ife North").stateCode("OS").lgaCode("OS013").build());
        lgas.add(Lgas.builder().lgaName("Ife South").stateCode("OS").lgaCode("OS014").build());
        lgas.add(Lgas.builder().lgaName("Ifedayo").stateCode("OS").lgaCode("OS015").build());
        lgas.add(Lgas.builder().lgaName("Ifelodun").stateCode("OS").lgaCode("OS016").build());
        lgas.add(Lgas.builder().lgaName("Ila").stateCode("OS").lgaCode("OS017").build());
        lgas.add(Lgas.builder().lgaName("Ilesa East").stateCode("OS").lgaCode("OS018").build());
        lgas.add(Lgas.builder().lgaName("Ilesa West").stateCode("OS").lgaCode("OS019").build());
        lgas.add(Lgas.builder().lgaName("Irepodun").stateCode("OS").lgaCode("OS020").build());
        lgas.add(Lgas.builder().lgaName("Irewole").stateCode("OS").lgaCode("OS021").build());
        lgas.add(Lgas.builder().lgaName("Isokan").stateCode("OS").lgaCode("OS022").build());
        lgas.add(Lgas.builder().lgaName("Iwo").stateCode("OS").lgaCode("OS023").build());
        lgas.add(Lgas.builder().lgaName("Obokun").stateCode("OS").lgaCode("OS024").build());
        lgas.add(Lgas.builder().lgaName("Odo Otin").stateCode("OS").lgaCode("OS025").build());
        lgas.add(Lgas.builder().lgaName("Ola Oluwa").stateCode("OS").lgaCode("OS026").build());
        lgas.add(Lgas.builder().lgaName("Olorunda").stateCode("OS").lgaCode("OS027").build());
        lgas.add(Lgas.builder().lgaName("Oriade").stateCode("OS").lgaCode("OS028").build());
        lgas.add(Lgas.builder().lgaName("Orolu").stateCode("OS").lgaCode("OS029").build());
        lgas.add(Lgas.builder().lgaName("Osogbo").stateCode("OS").lgaCode("OS030").build());
        lgas.add(Lgas.builder().lgaName("OSXXXX").stateCode("OS").lgaCode("OSXXX").build());
        lgas.add(Lgas.builder().lgaName("Ibadan North-East").stateCode("OY").lgaCode("OY001").build());
        lgas.add(Lgas.builder().lgaName("Ibadan South-West").stateCode("OY").lgaCode("OY002").build());
        lgas.add(Lgas.builder().lgaName("Ibadan South-East").stateCode("OY").lgaCode("OY003").build());
        lgas.add(Lgas.builder().lgaName("Ido").stateCode("OY").lgaCode("OY004").build());
        lgas.add(Lgas.builder().lgaName("Afijio").stateCode("OY").lgaCode("OY005").build());
        lgas.add(Lgas.builder().lgaName("Akinyele").stateCode("OY").lgaCode("OY006").build());
        lgas.add(Lgas.builder().lgaName("Egbeda").stateCode("OY").lgaCode("OY007").build());
        lgas.add(Lgas.builder().lgaName("Oluyole").stateCode("OY").lgaCode("OY008").build());
        lgas.add(Lgas.builder().lgaName("Ona Ara").stateCode("OY").lgaCode("OY009").build());
        lgas.add(Lgas.builder().lgaName("Lagelu").stateCode("OY").lgaCode("OY010").build());
        lgas.add(Lgas.builder().lgaName("Ogo Oluwa").stateCode("OY").lgaCode("OY011").build());
        lgas.add(Lgas.builder().lgaName("Surulere").stateCode("OY").lgaCode("OY012").build());
        lgas.add(Lgas.builder().lgaName("Ogbomosho North").stateCode("OY").lgaCode("OY013").build());
        lgas.add(Lgas.builder().lgaName("Ogbomosho South").stateCode("OY").lgaCode("OY014").build());
        lgas.add(Lgas.builder().lgaName("Atisbo").stateCode("OY").lgaCode("OY015").build());
        lgas.add(Lgas.builder().lgaName("Irepo").stateCode("OY").lgaCode("OY016").build());
        lgas.add(Lgas.builder().lgaName("Orelope").stateCode("OY").lgaCode("OY017").build());
        lgas.add(Lgas.builder().lgaName("Saki West").stateCode("OY").lgaCode("OY018").build());
        lgas.add(Lgas.builder().lgaName("Saki East").stateCode("OY").lgaCode("OY019").build());
        lgas.add(Lgas.builder().lgaName("Atiba").stateCode("OY").lgaCode("OY020").build());
        lgas.add(Lgas.builder().lgaName("Iwajowa").stateCode("OY").lgaCode("OY021").build());
        lgas.add(Lgas.builder().lgaName("Kajola").stateCode("OY").lgaCode("OY022").build());
        lgas.add(Lgas.builder().lgaName("Itesiwaju").stateCode("OY").lgaCode("OY023").build());
        lgas.add(Lgas.builder().lgaName("Ori Ire").stateCode("OY").lgaCode("OY024").build());
        lgas.add(Lgas.builder().lgaName("Olorunsogo").stateCode("OY").lgaCode("OY025").build());
        lgas.add(Lgas.builder().lgaName("Ibarapa Central").stateCode("OY").lgaCode("OY026").build());
        lgas.add(Lgas.builder().lgaName("Ibarapa East").stateCode("OY").lgaCode("OY027").build());
        lgas.add(Lgas.builder().lgaName("Ibarapa North").stateCode("OY").lgaCode("OY028").build());
        lgas.add(Lgas.builder().lgaName("Iseyin").stateCode("OY").lgaCode("OY029").build());
        lgas.add(Lgas.builder().lgaName("Oyo East").stateCode("OY").lgaCode("OY030").build());
        lgas.add(Lgas.builder().lgaName("Oyo").stateCode("OY").lgaCode("OY031").build());
        lgas.add(Lgas.builder().lgaName("Ibadan North").stateCode("OY").lgaCode("OY032").build());
        lgas.add(Lgas.builder().lgaName("Ibadan North-West").stateCode("OY").lgaCode("OY033").build());
        lgas.add(Lgas.builder().lgaName("OYXXXX").stateCode("OY").lgaCode("OYXXX").build());
        lgas.add(Lgas.builder().lgaName("Mangu").stateCode("PL").lgaCode("PL001").build());
        lgas.add(Lgas.builder().lgaName("Qua an Pan").stateCode("PL").lgaCode("PL002").build());
        lgas.add(Lgas.builder().lgaName("Bokkos").stateCode("PL").lgaCode("PL003").build());
        lgas.add(Lgas.builder().lgaName("Riyom").stateCode("PL").lgaCode("PL004").build());
        lgas.add(Lgas.builder().lgaName("Barkin Ladi").stateCode("PL").lgaCode("PL005").build());
        lgas.add(Lgas.builder().lgaName("Pankshin").stateCode("PL").lgaCode("PL006").build());
        lgas.add(Lgas.builder().lgaName("Kanam").stateCode("PL").lgaCode("PL007").build());
        lgas.add(Lgas.builder().lgaName("Kanke").stateCode("PL").lgaCode("PL008").build());
        lgas.add(Lgas.builder().lgaName("Jos North").stateCode("PL").lgaCode("PL009").build());
        lgas.add(Lgas.builder().lgaName("Jos South").stateCode("PL").lgaCode("PL010").build());
        lgas.add(Lgas.builder().lgaName("Jos East").stateCode("PL").lgaCode("PL011").build());
        lgas.add(Lgas.builder().lgaName("Bassa").stateCode("PL").lgaCode("PL012").build());
        lgas.add(Lgas.builder().lgaName("Mikang").stateCode("PL").lgaCode("PL013").build());
        lgas.add(Lgas.builder().lgaName("Shendam").stateCode("PL").lgaCode("PL014").build());
        lgas.add(Lgas.builder().lgaName("Langtang North").stateCode("PL").lgaCode("PL015").build());
        lgas.add(Lgas.builder().lgaName("Langtang South").stateCode("PL").lgaCode("PL016").build());
        lgas.add(Lgas.builder().lgaName("Wase").stateCode("PL").lgaCode("PL017").build());
        lgas.add(Lgas.builder().lgaName("PLXXXX").stateCode("PL").lgaCode("PLXXX").build());
        lgas.add(Lgas.builder().lgaName("Abua/Odual").stateCode("RI").lgaCode("RI001").build());
        lgas.add(Lgas.builder().lgaName("Ahoada East").stateCode("RI").lgaCode("RI002").build());
        lgas.add(Lgas.builder().lgaName("Ahoada West").stateCode("RI").lgaCode("RI003").build());
        lgas.add(Lgas.builder().lgaName("Akuku-Toru").stateCode("RI").lgaCode("RI004").build());
        lgas.add(Lgas.builder().lgaName("Andoni").stateCode("RI").lgaCode("RI005").build());
        lgas.add(Lgas.builder().lgaName("Asari-Toru").stateCode("RI").lgaCode("RI006").build());
        lgas.add(Lgas.builder().lgaName("Bonny").stateCode("RI").lgaCode("RI007").build());
        lgas.add(Lgas.builder().lgaName("Degema").stateCode("RI").lgaCode("RI008").build());
        lgas.add(Lgas.builder().lgaName("Eleme").stateCode("RI").lgaCode("RI009").build());
        lgas.add(Lgas.builder().lgaName("Emuoha").stateCode("RI").lgaCode("RI010").build());
        lgas.add(Lgas.builder().lgaName("Etche").stateCode("RI").lgaCode("RI011").build());
        lgas.add(Lgas.builder().lgaName("Gokana").stateCode("RI").lgaCode("RI012").build());
        lgas.add(Lgas.builder().lgaName("Ikwerre").stateCode("RI").lgaCode("RI013").build());
        lgas.add(Lgas.builder().lgaName("Khana").stateCode("RI").lgaCode("RI014").build());
        lgas.add(Lgas.builder().lgaName("Obio/Akpor").stateCode("RI").lgaCode("RI015").build());
        lgas.add(Lgas.builder().lgaName("Ogba/Egbema/Ndoni").stateCode("RI").lgaCode("RI016").build());
        lgas.add(Lgas.builder().lgaName("Ogu/Bolo").stateCode("RI").lgaCode("RI017").build());
        lgas.add(Lgas.builder().lgaName("Okrika").stateCode("RI").lgaCode("RI018").build());
        lgas.add(Lgas.builder().lgaName("Omuma").stateCode("RI").lgaCode("RI019").build());
        lgas.add(Lgas.builder().lgaName("Opobo/Nkoro").stateCode("RI").lgaCode("RI020").build());
        lgas.add(Lgas.builder().lgaName("Oyigbo").stateCode("RI").lgaCode("RI021").build());
        lgas.add(Lgas.builder().lgaName("Port Harcourt").stateCode("RI").lgaCode("RI022").build());
        lgas.add(Lgas.builder().lgaName("Tai").stateCode("RI").lgaCode("RI023").build());
        lgas.add(Lgas.builder().lgaName("RVXXXX").stateCode("RI").lgaCode("RIXXX").build());
        lgas.add(Lgas.builder().lgaName("Binji").stateCode("SO").lgaCode("SO001").build());
        lgas.add(Lgas.builder().lgaName("Bodinga").stateCode("SO").lgaCode("SO002").build());
        lgas.add(Lgas.builder().lgaName("Dange Shuni").stateCode("SO").lgaCode("SO003").build());
        lgas.add(Lgas.builder().lgaName("Gada").stateCode("SO").lgaCode("SO004").build());
        lgas.add(Lgas.builder().lgaName("Goronyo").stateCode("SO").lgaCode("SO005").build());
        lgas.add(Lgas.builder().lgaName("Gudu").stateCode("SO").lgaCode("SO006").build());
        lgas.add(Lgas.builder().lgaName("Gwadabawa").stateCode("SO").lgaCode("SO007").build());
        lgas.add(Lgas.builder().lgaName("Illela").stateCode("SO").lgaCode("SO008").build());
        lgas.add(Lgas.builder().lgaName("Isa").stateCode("SO").lgaCode("SO009").build());
        lgas.add(Lgas.builder().lgaName("Kebbe").stateCode("SO").lgaCode("SO010").build());
        lgas.add(Lgas.builder().lgaName("Kware").stateCode("SO").lgaCode("SO011").build());
        lgas.add(Lgas.builder().lgaName("Rabah").stateCode("SO").lgaCode("SO012").build());
        lgas.add(Lgas.builder().lgaName("Sabon Birni").stateCode("SO").lgaCode("SO013").build());
        lgas.add(Lgas.builder().lgaName("Shagari").stateCode("SO").lgaCode("SO014").build());
        lgas.add(Lgas.builder().lgaName("Silame").stateCode("SO").lgaCode("SO015").build());
        lgas.add(Lgas.builder().lgaName("Sokoto North").stateCode("SO").lgaCode("SO016").build());
        lgas.add(Lgas.builder().lgaName("Sokoto South").stateCode("SO").lgaCode("SO017").build());
        lgas.add(Lgas.builder().lgaName("Tambuwal").stateCode("SO").lgaCode("SO018").build());
        lgas.add(Lgas.builder().lgaName("Tangaza").stateCode("SO").lgaCode("SO019").build());
        lgas.add(Lgas.builder().lgaName("Tureta").stateCode("SO").lgaCode("SO020").build());
        lgas.add(Lgas.builder().lgaName("Wamako").stateCode("SO").lgaCode("SO021").build());
        lgas.add(Lgas.builder().lgaName("Wurno").stateCode("SO").lgaCode("SO022").build());
        lgas.add(Lgas.builder().lgaName("Yabo").stateCode("SO").lgaCode("SO023").build());
        lgas.add(Lgas.builder().lgaName("SOXXXX").stateCode("SO").lgaCode("SOXXX").build());
        lgas.add(Lgas.builder().lgaName("Ardo Kola").stateCode("TA").lgaCode("TA001").build());
        lgas.add(Lgas.builder().lgaName("Bali").stateCode("TA").lgaCode("TA002").build());
        lgas.add(Lgas.builder().lgaName("Donga").stateCode("TA").lgaCode("TA003").build());
        lgas.add(Lgas.builder().lgaName("Gashaka").stateCode("TA").lgaCode("TA004").build());
        lgas.add(Lgas.builder().lgaName("Gassol").stateCode("TA").lgaCode("TA005").build());
        lgas.add(Lgas.builder().lgaName("Ibi").stateCode("TA").lgaCode("TA006").build());
        lgas.add(Lgas.builder().lgaName("Jalingo").stateCode("TA").lgaCode("TA007").build());
        lgas.add(Lgas.builder().lgaName("Karim Lamido").stateCode("TA").lgaCode("TA008").build());
        lgas.add(Lgas.builder().lgaName("Kumi").stateCode("TA").lgaCode("TA009").build());
        lgas.add(Lgas.builder().lgaName("Lau").stateCode("TA").lgaCode("TA010").build());
        lgas.add(Lgas.builder().lgaName("Sardauna").stateCode("TA").lgaCode("TA011").build());
        lgas.add(Lgas.builder().lgaName("Takum").stateCode("TA").lgaCode("TA012").build());
        lgas.add(Lgas.builder().lgaName("Ussa").stateCode("TA").lgaCode("TA013").build());
        lgas.add(Lgas.builder().lgaName("Wukari").stateCode("TA").lgaCode("TA014").build());
        lgas.add(Lgas.builder().lgaName("Yorro").stateCode("TA").lgaCode("TA015").build());
        lgas.add(Lgas.builder().lgaName("Zing").stateCode("TA").lgaCode("TA016").build());
        lgas.add(Lgas.builder().lgaName("TAXXXX").stateCode("TA").lgaCode("TAXXX").build());
        lgas.add(Lgas.builder().lgaName("XXXXXX").stateCode("XX").lgaCode("XXXXX").build());
        lgas.add(Lgas.builder().lgaName("Bade").stateCode("YO").lgaCode("YO001").build());
        lgas.add(Lgas.builder().lgaName("Bursari").stateCode("YO").lgaCode("YO002").build());
        lgas.add(Lgas.builder().lgaName("Damaturu").stateCode("YO").lgaCode("YO003").build());
        lgas.add(Lgas.builder().lgaName("Fika").stateCode("YO").lgaCode("YO004").build());
        lgas.add(Lgas.builder().lgaName("Fune").stateCode("YO").lgaCode("YO005").build());
        lgas.add(Lgas.builder().lgaName("Geidam").stateCode("YO").lgaCode("YO006").build());
        lgas.add(Lgas.builder().lgaName("Gujba").stateCode("YO").lgaCode("YO007").build());
        lgas.add(Lgas.builder().lgaName("Gulani").stateCode("YO").lgaCode("YO008").build());
        lgas.add(Lgas.builder().lgaName("Jakusko").stateCode("YO").lgaCode("YO009").build());
        lgas.add(Lgas.builder().lgaName("Karasuwa").stateCode("YO").lgaCode("YO010").build());
        lgas.add(Lgas.builder().lgaName("Machina").stateCode("YO").lgaCode("YO011").build());
        lgas.add(Lgas.builder().lgaName("Nangere").stateCode("YO").lgaCode("YO012").build());
        lgas.add(Lgas.builder().lgaName("Nguru").stateCode("YO").lgaCode("YO013").build());
        lgas.add(Lgas.builder().lgaName("Potiskum").stateCode("YO").lgaCode("YO014").build());
        lgas.add(Lgas.builder().lgaName("Tarmuwa").stateCode("YO").lgaCode("YO015").build());
        lgas.add(Lgas.builder().lgaName("Yunusari").stateCode("YO").lgaCode("YO016").build());
        lgas.add(Lgas.builder().lgaName("Yusufari").stateCode("YO").lgaCode("YO017").build());
        lgas.add(Lgas.builder().lgaName("YOXXXX").stateCode("YO").lgaCode("YOXXX").build());
        lgas.add(Lgas.builder().lgaName("ZAXXXX").stateCode("ZA").lgaCode("ZAXXX").build());

        lgaRepository.saveAll(lgas);

        System.out.println("All LGAs seeded successfully.");
    }
}
