#spring.profiles.active=local

#spring.profiles.active=local
#spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=${SPRING_PROFILES_ACTIVE}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Enable Eureka Client
eureka.client.enabled=true

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Health check (disable if you don't want failures due to Eureka issues)
eureka.client.healthcheck.enabled=false

# Retry and timeout settings
eureka.client.initial-instance-info-replication-interval-seconds=40
eureka.client.registry-fetch-interval-seconds=40
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Log and diagnostics
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG

#==========================Fineract==========================================================
corepay.api.name=CorePayApi
bills.api.name=bills
bills.payment.api.base.url=${BILLS_PAYMENT_API_BASE_URL}
corepay.api.base.url=${COREPAY_API_BASE_URL}

nameenquiry.api.name=${NAMEENQUIRY_API_NAME}
nameenquiry.api.base.url=${NAMEENQUIRY_API_BASE_URL}

feign.auth=${FEIGN_AUTH}
client.url=${CLIENT_URL:http://63.250.32.84:32001/set-pin?code=}

#==========================Cron Job Timing==========================================================
cron.entity.account=0 */1 * * * *
#cron.run.entity.account=0 */30 * * * *

echannel.api.name=Statement
echannel.api.base.url=${ECHANNEL_API_BASE_URL}

spring.boot.admin.client.url=${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:8400}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL:http://tms_discovery:neptune123@localhost:8200/eureka}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#mongodb+srv://kunlethompson2:MWxmLIykHbnOzAAS@paydb.3mvwp.mongodb.net
#spring.data.mongodb.database=paydb
#spring.data.mongodb.uri=mongodb://kunlethompson2:MWxmLIykHbnOzAAS@paydb.3mvwp.mongodb.net
#spring.data.mongodb.uri=mongodb+srv://kunlethompson2:MWxmLIykHbnOzAAS@paydb.3mvwp.mongodb.net
spring.data.mongodb.database=paydb
grpc.customer.request.port=${GRPC_CUSTOMER_REQUEST_PORT}
grpc.customer.request.url=${GRPC_CUSTOMER_REQUEST_URL}
grpc.customer.product.id={GRPC_CUSTOMER_PRODUCT_ID}
grpc.virtual.request.port=${GRPC_VIRTUAL_REQUEST_PORT}
grpc.virtual.request.url=${GRPC_VIRTUAL_REQUEST_URL}
grpc.auth.request.port=${GRPC_AUTH_REQUEST_PORT}
grpc.notifications.port=${GRPC_NOTIFICATIONS_PORT}
grpc.notifications.url=${GRPC_NOTIFICATIONS_URL}
grpc.auth.request.url=${GRPC_AUTH_REQUEST_URL}
grpc.debitCredit.webhook.url=${GRPC_DEBITCREDIT_WEBHOOK_URL}
grpc.easypay.request.url=${GRPC_EASYPAY_REQUEST_URL}
grpc.easypay.request.port=${GRPC_EASYPAY_REQUEST_PORT}
grpc.debitCredit.request.url=${GRPC_DEBITCREDIT_REQUEST_URL}
grpc.debitCredit.request.port=${GRPC_DEBITCREDIT_REQUEST_PORT}
secret.key=${SECRET_KEY}
grpc.printable.url=${GRPC_PRINTABLE_URL}
grpc.printable.port=${GRPC_PRINTABLE_PORT}

pushy.secret=${PUSHY_SECRET}

aes.iv=${AES_IV}
aes.algo=${AES_ALGO}
aes.key=${AES_KEY}

#https://tangible.youtrack.cloud/articles/TAN-A-28/Tech-Onboarding
#https://tangible.youtrack.cloud/articles/TAN-A-27/Product-Onboarding


#======================SSL Configuration=======================================
#server.ssl.enabled=true
#server.ssl.key-store-password=pos123
#server.ssl.key-store=classpath:nvault_com_ng.pfx
#server.ssl.key-store-type=PKCS12

#==========================Fineract==========================================================
#corepay.api.base.url=https://203.161.43.149:8443/fineract-provider/api/v1/

grpc.debitCredit.charge.ledger_code=${GRPC_DEBITCREDIT_CHARGE_LEDGER_CODE}
grpc.debitCredit.transaction.ledger_code=${GRPC_DEBITCREDIT_TRANSACTION_LEDGER_CODE}